<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Client;

class ClientSeeder extends Seeder
{
    public function run()
    {
        $clients = [
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20419387658',
                'business_name'  => 'CEMENTOS PACASMAYO S.A.A.',
                'description'    => '',
                'address'        => 'CAL. LA COLONIA NRO. 150 URB. EL VIVERO LIMA - LIMA - SANTIA',
                'contact_phone'  => '999999999',
                'contact_email'  => 'CEMENTOS@PACASMAYO.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20600180631',
                'business_name'  => 'AGROAURORA S.A.C.',
                'description'    => '',
                'address'        => 'AV.REPUBLICA DE PANAMA 2461 LA VICTORIA - LIMA',
                'contact_phone'  => '999999999',
                'contact_email'  => 'AGRO@AURORA.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20116225779',
                'business_name'  => 'AGROINDUSTRIAS SAN JACINTO S.A.A.',
                'description'    => '',
                'address'        => 'AV. PARQUE FABRICA NRO. S/N. (OFICINAS DE LA EMPRESA CASA GR',
                'contact_phone'  => '999999999',
                'contact_email'  => 'AGRO@INDUSTRIAS.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20547999691',
                'business_name'  => 'AGROLMOS S.A.',
                'description'    => '',
                'address'        => 'AV. PARQUE FABRICA NRO. S/N (X AV.CENTRAL EX HOSPITAL DE CAS',
                'contact_phone'  => '999999999',
                'contact_email'  => 'AGRO@OLMOS.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20512773924',
                'business_name'  => 'ANDALUCITA S.A.',
                'description'    => '',
                'address'        => 'AV. MATERIALES NRO. 2828 INT. 1 (ALTURA CDRA 7 DE AV UNIVERS',
                'contact_phone'  => '999999999',
                'contact_email'  => 'ANDALUCITA@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20131823020',
                'business_name'  => 'CASA GRANDE S.A.A.',
                'description'    => '',
                'address'        => 'AV. PARQUE FABRICA NRO. S/N LA LIBERTAD - ASCOPE - CASA GRAN',
                'contact_phone'  => '999999999',
                'contact_email'  => 'CASA@GRANDE.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20131867744',
                'business_name'  => 'CARTAVIO S.A.A.',
                'description'    => '',
                'address'        => 'AV. PARQUE FABRICA NRO. S/N. (OFICINAS DE LA EMPRESA CASA GR',
                'contact_phone'  => '999999999',
                'contact_email'  => 'CATAVIO@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20506285314',
                'business_name'  => 'COMPAÑIA MINERA MISKI MAYO S.R.L.',
                'description'    => '',
                'address'        => 'CAL.DIONISIO DERTEANO NRO. 184 INT. 301 URB. SANTA ANA (EDIF',
                'contact_phone'  => '999999999',
                'contact_email'  => 'MISKI@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20546128424',
                'business_name'  => 'DSM MARINE LIPIDS PERU S.A.C.',
                'description'    => '',
                'address'        => 'AV. LOS GALLOS MZA. A LOTE. 03 URB. LAS PRADERAS DE LURIN (A',
                'contact_phone'  => '999999999',
                'contact_email'  => 'DSM@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20602674127',
                'business_name'  => 'GAT PERU S.A.C.',
                'description'    => '',
                'address'        => 'AV. MARISCAL JOSE DE LA MAR NRO. 550 INT. 302 URB. SANTA CRU',
                'contact_phone'  => '999999999',
                'contact_email'  => 'GAT@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20479569780',
                'business_name'  => 'GOBIERNO REGIONAL LAMBAYEQUE',
                'description'    => '',
                'address'        => 'AV. JUAN TOMIS STACK KM. 4.5 LAMBAYEQUE - CHICLAYO - CHICLAY',
                'contact_phone'  => '999999999',
                'contact_email'  => 'GOBIERNO@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20525728600',
                'business_name'  => 'PLASTICOS AGRICOLAS Y GEOMEMBRANAS S.A.C.',
                'description'    => '',
                'address'        => 'CARRETERA PAITA-SULLANA KM 3 NRO. . MZA A LOTE 10 Y 11 - ZED',
                'contact_phone'  => '999999999',
                'contact_email'  => 'PLASTICOS@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20131644524',
                'business_name'  => 'DISTRIBUIDORA NORTE PACASMAYO SRL',
                'description'    => '',
                'address'        => 'CAL.LA COLONIA NRO. 150 URB. EL VIVERO LIMA - LIMA - SANTIAG',
                'contact_phone'  => '999999999',
                'contact_email'  => 'DINO@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20600094212',
                'business_name'  => 'PROCESOS MUCHIK S.R.L.',
                'description'    => '',
                'address'        => 'CAR.AV. PANAMERICANA NORTE KM. 777 OTR. CHOSICA DEL NORTE (F',
                'contact_phone'  => '999999999',
                'contact_email'  => 'MUCHIK@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20517834255',
                'business_name'  => 'INVERSIONES PRISCO S.A.C.',
                'description'    => '',
                'address'        => 'DERBY NRO. 250 INT. 201 URB. EL DERBY LIMA - LIMA - SANTIAGO',
                'contact_phone'  => '999999999',
                'contact_email'  => 'PRISCO@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20517270297',
                'business_name'  => 'CLEAN ENERGY DEL PERU S.R.L.',
                'description'    => '',
                'address'        => 'AV. UNIVERSITARIA SUR NRO. 415 Z.I. INDUSTRIAL (CRUCE CON AV',
                'contact_phone'  => '999999999',
                'contact_email'  => 'ENERGY@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20136165667',
                'business_name'  => 'PESQUERA HAYDUK S.A.',
                'description'    => '',
                'address'        => 'AV. MANUEL OLGUIN NRO. 501 URB. HARAS TYBER LIMA - LIMA - SA',
                'contact_phone'  => '999999999',
                'contact_email'  => 'PESQUERA@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20530184596',
                'business_name'  => 'ECOSAC AGRICOLA S.A.C.',
                'description'    => '',
                'address'        => 'CAR.CHAPAIRA NRO. S-N CAS. CHAPAIRA (FRENTE AL CASERIO CHAPA',
                'contact_phone'  => '999999999',
                'contact_email'  => 'ECOSAC@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20608275143',
                'business_name'  => 'CORPORACION PLASTIC GL S.A.C.',
                'description'    => '',
                'address'        => 'MZA. E LOTE. 16 ASC. CASA HUERTA SAN PEDRO LIMA - LIMA - PUE',
                'contact_phone'  => '999999999',
                'contact_email'  => 'CORPORACION@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20132377783',
                'business_name'  => 'AGROINDUSTRIAL LAREDO S.A.A.',
                'description'    => '',
                'address'        => 'AV. TRUJILLO NRO. S/N ZONA INDUST. LAREDO (LOS JARDINES LARE',
                'contact_phone'  => '999999999',
                'contact_email'  => 'AGROINDUS@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20418453177',
                'business_name'  => 'TRUPAL S.A.',
                'description'    => '',
                'address'        => 'AV. EVITAMIENTO NRO. 3636 (ALTURA DEL PUENTE NUEVO) LIMA - L',
                'contact_phone'  => '999999999',
                'contact_email'  => 'NXNNKN@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20204844381',
                'business_name'  => 'EL ROCIO S.A.',
                'description'    => '',
                'address'        => 'CAR.INDUSTRIAL LAREDO KM. NRO. 1.5 ZONA INDUSTRIAL LA LIBERT',
                'contact_phone'  => '999999999',
                'contact_email'  => 'VGHASDGSAV@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20451779711',
                'business_name'  => 'SOCIEDAD AGRICOLA RAPEL S.A.C.',
                'description'    => '',
                'address'        => 'MZA. O CAS. EL PAPAYO. CASTILLA. PIURA, PERÚ',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20530216625',
                'business_name'  => 'PLANTA DE POSTES PIURA S.R.L.',
                'description'    => '',
                'address'        => 'MZA. A2 LOTE. 35 PIURA (MEDIA CDRA ANTES DE CALLE CASTRO POZ',
                'contact_phone'  => '',
                'contact_email'  => 'MARELLANO@PPP.COM.PE',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20161749126',
                'business_name'  => 'CONGRESO DE LA REPUBLICA',
                'description'    => '',
                'address'        => 'Jr. Huallaga N° 358 – Lima',
                'contact_phone'  => '',
                'contact_email'  => 'msalvador@congreso.gob.pe',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20370146994',
                'business_name'  => 'CORPORACION ACEROS AREQUIPA S.A.',
                'description'    => '',
                'address'        => 'CAR.PANAMERICANA SUR NRO. 241 PANAMERICANA SUR ICA - PISCO -',
                'contact_phone'  => '999999999',
                'contact_email'  => 'HSAHDG@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '11900013300',
                'business_name'  => 'MONTERREY AZUCARERA LOJANA C.A.',
                'description'    => '',
                'address'        => 'ECUADOR',
                'contact_phone'  => '999999999',
                'contact_email'  => 'EFS@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20542232006',
                'business_name'  => 'CAYNARACHI S.A.',
                'description'    => '',
                'address'        => 'PJ. CASTILLA NRO. 187 (JR.LOS GIRASOLES CUADRA 3-BARRIO HUAY',
                'contact_phone'  => '',
                'contact_email'  => 'NGUEVARA@CAYNARACHI.COM.PE',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20602266916',
                'business_name'  => 'CONSORCIO CARSOL - JRM S.A.C.',
                'description'    => '',
                'address'        => 'CAL.JUNIN SUR NRO. 658 CERCADO URBANO (COCHERA COSTA DEL SOL',
                'contact_phone'  => '999999999',
                'contact_email'  => 'SFSDF@GMAIL.COM',
                'logo'           => null,
            ],

            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20525413447',
                'business_name'  => 'AGRICOLA DEL CHIRA S.A.',
                'description'    => '',
                'address'        => 'AV. LOS TALLANES MZA. E LOTE. 3 URB. SAN EDUARDO (FRENTE A L',
                'contact_phone'  => '999999999',
                'contact_email'  => 'GHCJBCHJ@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20100128218',
                'business_name'  => 'PETROLEOS DEL PERU S.A.',
                'description'    => '',
                'address'        => 'AV. ENRIQUE CANAVAL MOREYRA NRO. 150 LIMA - LIMA - SAN ISIDR',
                'contact_phone'  => '999999999',
                'contact_email'  => 'BSDJDS@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20131257750',
                'business_name'  => 'SEGURO SOCIAL DE SALUD',
                'description'    => '',
                'address'        => 'AV. DOMINGO CUETO NRO. 120 LIMA - LIMA - JESUS MARIA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20100153832',
                'business_name'  => 'UNNA ENERGIA S.A.',
                'description'    => '',
                'address'        => 'AV. PETIT THOUARS NRO. 4957 LIMA - LIMA - MIRAFLORES',
                'contact_phone'  => '999999999',
                'contact_email'  => 'BDMNDSM@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '2017495097',
                'business_name'  => 'UNIVERSIDAD NACIONAL DE EDUCACIÓN ENRIQUE GUZMÁN Y VALLE',
                'description'    => '',
                'address'        => 'AV. ENRIQUE GUZMAN Y VAL NRO. S/N URB. LA CANTUTA (ALT.KM.35',
                'contact_phone'  => '999999999',
                'contact_email'  => 'HSHDSDSJ@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20600581768',
                'business_name'  => 'OCEANO SEAFOOD S.A.',
                'description'    => '',
                'address'        => 'AV. MANUEL OLGUIN NRO. 211 INT. 4 (TORRE OMEGA-PISO 4) LIMA',
                'contact_phone'  => '999999999',
                'contact_email'  => 'DASFAEAE@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20607713546',
                'business_name'  => 'MILICIC PERU S.A.C.',
                'description'    => '',
                'address'        => 'AV. REPUBLICA DE PANAMA NRO. 3418 INT. 1601 URB. LIMATAMBO L',
                'contact_phone'  => '999999999',
                'contact_email'  => 'MILICIC@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20601116082',
                'business_name'  => 'CHINA RAILWAY N° 10 ENGINEERING GROUP CO., LTD SUCURSAL DEL ',
                'description'    => '',
                'address'        => 'CAL.DEAN VALDIVIA NRO. 243 INT. 601 URB. JARDIN LIMA - LIMA ',
                'contact_phone'  => '999999999',
                'contact_email'  => 'JORGEZUNIGA.S@HOTMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20604175756',
                'business_name'  => 'YOFC PERU S.A.C.',
                'description'    => '',
                'address'        => 'AV. ENRIQUE CANAVAL Y MOREIRA NRO. 480 INT. 1500 URB. LIMATA',
                'contact_phone'  => '999999999',
                'contact_email'  => 'NDFENFK@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20329725431',
                'business_name'  => 'SUNSHINE EXPORT S.A.C',
                'description'    => '',
                'address'        => 'CAR.TAMBOGRANDE-LAS LOMAS KM. 1077 (CAR. TAMBOGRANDE-LAS LOM',
                'contact_phone'  => '999999999',
                'contact_email'  => 'HJBDFBEH@GMAIL.COM',
                'logo'           => null,
            ],

            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20603046472',
                'business_name'  => 'PESQUERA ALTAIR S.A.C.',
                'description'    => '',
                'address'        => 'AV. MANUEL OLGUIN NRO. 211 DPTO. 101 INT. 401 URB. LOS GRANA',
                'contact_phone'  => '999999999',
                'contact_email'  => 'PALTAIR@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20172606777',
                'business_name'  => 'UNIVERSIDAD NACIONAL DE PIURA',
                'description'    => '',
                'address'        => 'CAR.A CASERIO MIRAFLORES NRO. S/N (CAMPUS UNIVERSITARIO) PIU',
                'contact_phone'  => '',
                'contact_email'  => 'UNP.EDU@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20539249640',
                'business_name'  => 'SAT- SAT INDUSTRIALES S.A.C',
                'description'    => '',
                'address'        => 'URBANIZACION PRIMAVERA MZ E LOTE 14',
                'contact_phone'  => '951901028',
                'contact_email'  => 'KARIA.TROYA@SAT-INDUSTRIALES.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20539244923',
                'business_name'  => 'LADRINORTE S.A.C.',
                'description'    => '',
                'address'        => 'MZA. A LOTE. S/N CAS. SAN MIGUEL (ALTURA DEL PEAJE, LADO IZQUIERDO)',
                'contact_phone'  => '999999999',
                'contact_email'  => 'VDHB@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20570526350',
                'business_name'  => 'HOSPITAL JOSE HERNÁN SOTO CADENILLAS.',
                'description'    => '',
                'address'        => 'JR. TARAPACA NRO. 565 BAR. SAN PEDRO CHOTA - CHOTA - CAJAMARCA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20555271566',
                'business_name'  => 'VITAPRO S.A.',
                'description'    => '',
                'address'        => '---',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20603778180',
                'business_name'  => 'AGROFUTURA COMPANY S.A.C.',
                'description'    => '',
                'address'        => 'AV. PARQUE FABRICA NRO. S/N -- (OFICINAS DE LA EMPRESA CASA GRANDE) LA LIBERTAD - ASCOPE - CASA GRANDE',
                'contact_phone'  => '999999999',
                'contact_email'  => 'AGROFUTURACOMPANY@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20112919377',
                'business_name'  => 'INSTITUTO GEOLÓGICO, MINERO Y METALÚRGICO –INGEMMET',
                'description'    => '',
                'address'        => 'AV. CANADA NRO 1470 – SAN BORJA',
                'contact_phone'  => '',
                'contact_email'  => 'CONTRATACIONESUL07@INGEMMET.GOB.PE',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20539927494',
                'business_name'  => 'DANPER AGRICOLA OLMOS S.A.C.',
                'description'    => '',
                'address'        => 'CAR.INDUSTRIAL A LAREDO NRO. S/N FND. BARRIO NUEVO (A150 MTS OVALO LA MARINA CAMINO A LAREDO) LA LIBERTAD - TRUJILLO - MOCHE',
                'contact_phone'  => '999999999',
                'contact_email'  => 'DANPER@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20529945192',
                'business_name'  => 'CORPORACION PESQUERA DEL MAR S.A.C.',
                'description'    => '',
                'address'        => 'MZA. C LOTE. 13 A.H. JOSE OLAYA (ALTURA DE COLEGIO JOSE OLAYA) PIURA - PIURA - PIURA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],

            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20480943687',
                'business_name'  => 'AVO AMERICA S.A.C.',
                'description'    => '',
                'address'        => 'ANCON 142 URB. SANTA VICTORIA -CHICLAYO',
                'contact_phone'  => '986650285',
                'contact_email'  => 'MRODRIGUEZ@AVOAMERICA.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20609746727',
                'business_name'  => 'GALILEO TECHNOLOGIES CORPORATION SUCURSAL PERÚ',
                'description'    => '',
                'address'        => 'CAL.GERMAN SCHREIBER NRO. 240 INT. 402 URB. SANTA ANA LIMA - LIMA - SAN ISIDRO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20555757469',
                'business_name'  => 'AVOCADO PACKING COMPANY S.A.C.',
                'description'    => '',
                'address'        => 'AV. MANUEL OLGUIN NRO. 335 INT. 1202 URB. LOS GRANADOS LIMA - LIMA - SANTIAGO DE SURCO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20329545459',
                'business_name'  => 'MANPOWER PROFESSIONAL SERVICES S.A.',
                'description'    => '',
                'address'        => 'CAL.MONTEROSA NRO. 233 URB. CHACARILLA DEL ESTANQUE (PISO 11) LIMA - LIMA - SANTIAGO DE SURCO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20170040938',
                'business_name'  => 'DANPER TRUJILLO S.A.C.',
                'description'    => '',
                'address'        => 'CAR.INDUSTRIAL A LAREDO NRO. SN FND. BARRIO NUEVO (A150 MTS OVALO LA MARINA CAMINO A LAREDO) LA LIBERTAD - TRUJILLO - MOCHE',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20440452494',
                'business_name'  => 'JEEMPAS E.I.R.L.',
                'description'    => '',
                'address'        => 'PROLONGACION ESPINAR NRO. 473 SECTOR CERCADO LA LIBERTAD - PACASMAYO - PACASMAYO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20100070970',
                'business_name'  => 'SUPERMERCADOS PERUANOS S.A.',
                'description'    => '',
                'address'        => 'CAL.MORELLI NRO. 181 INT. P-2 LIMA - LIMA - SAN BORJA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20535715069',
                'business_name'  => 'CONSORCIO PIURA',
                'description'    => '',
                'address'        => 'AV. DEL PARQUE SUR NRO. 668 URB. CORPAC LIMA - LIMA - SAN BORJA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20600957652',
                'business_name'  => 'PAITA INGREDIENTS S.A.C.',
                'description'    => '',
                'address'        => 'CAR.PAITA SULLANA KM.3 S/N LOTE. B Z.I. ZED PAITA PIURA - PAITA - PAITA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20484084948',
                'business_name'  => 'TRANSPORTES Y SERVICIOS GENERALES LARA E.I.R.L.',
                'description'    => '',
                'address'        => 'NRO. SN CAS. CALLEJON LOS MEDANOS (CRUCE DEL PARQUE KURT BEER LA LEGUA) PIURA - PIURA - CATACAOS',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],

            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20102762925',
                'business_name'  => 'EPS GRAU S.A.',
                'description'    => '',
                'address'        => 'JR. ZELAYA LA ARENA NRO. S.N. URB. SANTA ANA (TANQUE ELEVADO DE AGUA DE SANTA ANA) PIURA - PIURA - PIURA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],

            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20549152091',
                'business_name'  => 'SUPERFOODS PERU S.A.C.',
                'description'    => '',
                'address'        => 'CAL. 6 MZA. K LOTE. 07-LA MERCED DE MONTERRICO - ATE,LIMA, PERÚ',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20491975602',
                'business_name'  => 'ALMACENES SUDAMERICANOS S.A.',
                'description'    => '',
                'address'        => 'AV. MANUEL OLGUIN NRO. 327 DPTO. 605 URB. LOS GRANADOS LIMA - LIMA - SANTIAGO DE SURCO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20508558997',
                'business_name'  => 'V & C CORPORATION S.A.C.',
                'description'    => '',
                'address'        => 'MZA. S LOTE. 1 ASC VILLA RICA CHACLACAYO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20100246172',
                'business_name'  => 'CEYESA INGENIERIA ELECTRICA S.A.',
                'description'    => '',
                'address'        => 'AV. ENRIQUE MEIGGS NRO. 255 Z.I. PARQ.INT.IND. Y COMERCIO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20536878573',
                'business_name'  => 'GASES DEL PACIFICO S.A.C.',
                'description'    => '',
                'address'        => 'AV. LAS ORQUIDEAS NRO. 585 DPTO. 1102 (EDIFÍCIO FIBRA PISO 11) LIMA - LIMA - SAN ISIDRO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20601803730',
                'business_name'  => 'CONSORCIO MONTE AZUL S.A.C.',
                'description'    => '',
                'address'        => 'MZA. M LOTE. 10 GRU. 21-A (SECTOR 2) LIMA - LIMA - VILLA EL SALVADOR',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20209133394',
                'business_name'  => 'MINERA BOROO MISQUICHILCA S.A.',
                'description'    => '',
                'address'        => 'AV. SANTO TORIBIO NRO. 173 INT. 301 URB. SAN ISIDRO (EDIFICIO REAL 8-VIA CENTRAL 125-131) LIMA - LIMA - SAN ISIDRO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20525313736',
                'business_name'  => 'INMOBILIARIA LAS CUMBRES S.A.C',
                'description'    => '',
                'address'        => 'AV FORTUNATO CHIRICHIGNO S/N MZ. LT.06 NRO. S/N FUNDO LA HACIENDA EL CHIPE FUNDO EL CHIPE (AL COSTADO DEL CUARTO PUENTE) PIURA - PIURA - PIURA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20538763072',
                'business_name'  => 'EMPRESA DE CREDITOS INVERSIONES LA CRUZ S.A.',
                'description'    => '',
                'address'        => 'AV. GUARDIA CIVIL NRO. 1260 URB. CORPAC LIMA - LIMA - SAN ISIDRO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20439348641',
                'business_name'  => 'MV SERVICIOS S.R.L.',
                'description'    => '',
                'address'        => 'CAL.MANCO CAPAC NRO. 42 LA LIBERTAD - PACASMAYO - PACASMAYO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20538349730',
                'business_name'  => 'KAESER COMPRESORES DE PERU S.R.L.',
                'description'    => '',
                'address'        => 'CAR. AUTOPISTA PANAMERICANA SUR 2001 KM. 38 INT. B26 OTR. CENTRO LOGÍSTICO BSF ALMACENES DEL PERU LIMA - LIMA - PUNTA HERMOSA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20480300336',
                'business_name'  => 'FAMEGSA E.I.R.L.',
                'description'    => '',
                'address'        => 'URBANIZACION PROGRESIVA LATINA MZA. A LOTE. 2',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20606506512',
                'business_name'  => 'SMART BUSINESS TEC S.A.C.',
                'description'    => '',
                'address'        => 'JR. BORGOÑO NRO. 152 URB. EL MOLINO LA LIBERTAD - TRUJILLO - TRUJILLO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20601285941',
                'business_name'  => 'GLOBAL CITRUS INTERNATIONAL S.A.C.',
                'description'    => '',
                'address'        => 'CAL.LAS CAMELIAS NRO. 185 INT. 803 URB. JARDIN LIMA - LIMA - SAN ISIDRO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20560157283',
                'business_name'  => 'SERVICIOS GENERALES GADENN E.I.R.L.',
                'description'    => '',
                'address'        => 'CAL.CHEPEN NRO. 756 SEC. CERCADO (A UNA CUADRA DEL MERCADO ZONAL) LA LIBERTAD - PACASMAYO - PACASMAYO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20438989812',
                'business_name'  => 'F & H TRANSPORTES Y SERVICIOS S.A.C.',
                'description'    => '',
                'address'        => 'AV. TUPAC AMARU NRO. 1637 URB. ALTO MOCHICA LA LIBERTAD - TRUJILLO - TRUJILLO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20131376503',
                'business_name'  => 'SERVIC NAC DE ADIESTRAM EN TRABAJ INDUST (SENATI)',
                'description'    => '',
                'address'        => 'AV. ALFREDO MENDIOLA NRO. 3520 (CARR. PANAMERICANA NORTE KM. 15.2) LIMA - LIMA - INDEPENDENCIA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20513632569',
                'business_name'  => 'MARINASOL S.A.',
                'description'    => '',
                'address'        => 'AV. EL DERBY NRO. 250 URB. EL DERBY DE MONTERRICO (PISO 4) LIMA - LIMA - SANTIAGO DE SURCO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20110366516',
                'business_name'  => 'CITRICOS PERUANOS S.A.',
                'description'    => '',
                'address'        => 'AV. PASEO DE LA REPUBLICA NRO. 3195 INT. 902 URB. CORPAC (FRENTE A TOTTUS) LIMA - LIMA - SAN ISIDRO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],

            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20110378956',
                'business_name'  => 'AGROMAR INDUSTRIAL S.A.',
                'description'    => '',
                'address'        => 'AV. PASEO DE LA REPÚBLICA 3195, URB. CORPAC OF. 901 - 902, SAN ISIDRO, LIMA 27 PERÚ',
                'contact_phone'  => '014410647',
                'contact_email'  => 'AGROMAR@AGROMARINDUSTRIAL.COM.PE',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20603335296',
                'business_name'  => 'PUFFER PERU S.R.L.',
                'description'    => '',
                'address'        => 'CAL. RIO DE LA PLATA NRO. 167 INT. 404',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20566078032',
                'business_name'  => 'NATIONAL FACILITIES MANAGEMENT S.A.C.',
                'description'    => '',
                'address'        => 'AV. REPUBLICA DE PANAMA NRO. 3531 INT. 601 URB. EL PALOMAR LIMA - LIMA - SAN ISIDRO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20265690361',
                'business_name'  => 'LARCO MAR S.A.',
                'description'    => '',
                'address'        => 'LIMA - PERU',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20505120702',
                'business_name'  => 'TECNICA AVICOLA S.A.',
                'description'    => '',
                'address'        => 'AV. JOSE PARDO NRO. 434 INT. 1201 LIMA - LIMA - MIRAFLORES',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20483957590',
                'business_name'  => 'PROVEEDORA DE PRODUCTOS MARINOS S.A.C.',
                'description'    => '',
                'address'        => 'PAITA - PIURA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20206228815',
                'business_name'  => 'PERUVIAN SEA FOOD S.A.',
                'description'    => '',
                'address'        => 'AV. MANUEL OLGUIN NRO. 325 DPTO. 907',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20293331066',
                'business_name'  => 'PRECISION PERU S.A.',
                'description'    => '',
                'address'        => 'VIA EXPRESA LUIS FERNAN B NRO. 2131',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20605908811',
                'business_name'  => 'EMBOTELLADORA CARAL S.A.C.',
                'description'    => '',
                'address'        => 'OTR. PREDIO RURAL HUANDO PARCE NRO. 55 OTR. ZONA CAMPO GRANDE -EX FUN',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20392776975',
                'business_name'  => 'MINERA SHOUXIN PERU S.A.',
                'description'    => '',
                'address'        => 'AV. REPUBLICA DE CHILE NRO. 262 (PS 8)',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20600467035',
                'business_name'  => 'INDUSTRIAS DEL TULUMAYO S.A.',
                'description'    => '',
                'address'        => 'PUCALLPA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20351410061',
                'business_name'  => 'OLEAGINOSAS AMAZONICAS S.A',
                'description'    => '',
                'address'        => 'LOS FRUTALES NRO. 249 CALLERIA CORONEL PORTILLO - UCAYALI PERÚ',
                'contact_phone'  => '923072002',
                'contact_email'  => 'ADMINISTRACION@OLAMSA.COM.PE',
                'logo'           => null,
            ],

            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20525512267',
                'business_name'  => 'REFRIGERADOS FISHOLG & HIJOS SOCIEDAD ANONIMA CERRADA',
                'description'    => '',
                'address'        => 'AV. LOS DIAMANTES MZA. C LOTE. 02 Z.I. ZONA INDUSTRIAL II',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20484251861',
                'business_name'  => 'PRODUCTORA ANDINA DE CONGELADOS S.R.L.',
                'description'    => '',
                'address'        => 'CAR. TAMBOGRANDE KM. 2.1 MZA. C LOTE. 05 Z.I. Z. INDUSTRIAL MUNICIPAL 1- SULLANA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20601229201',
                'business_name'  => 'OCHO SUR P S.A.C.',
                'description'    => '',
                'address'        => 'PUCALLPA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20163898200',
                'business_name'  => 'EMPRESA AGROINDUSTRIAL POMALCA S.A.A.',
                'description'    => '',
                'address'        => 'CAR. CHICLAYO A CHONGOYAPE KM. 07 (FRENTE A LA IGLESIA DE POMALCA)',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20514134155',
                'business_name'  => 'LATERCER S.A.C.',
                'description'    => '',
                'address'        => 'AV. LAS TORRES MZA. S-N LOTE. 27 FND. EX FUNDO HUACHIPA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20523611250',
                'business_name'  => 'H2OLMOS S.A.',
                'description'    => '',
                'address'        => 'LAMBAYEQUE',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20600409604',
                'business_name'  => 'INSUMOS CORPORATIVOS PERU E.I.R.L.',
                'description'    => '',
                'address'        => 'AV. ALFREDO MENDIOLA NRO. 973 LIMA - LIMA - SAN MARTIN DE PORRES',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20224748711',
                'business_name'  => 'CORPORACIÓN PESQUERA INCA S.A.C.',
                'description'    => '',
                'address'        => 'AV. MANUEL OLGUIN NRO. 325 INT. 1501 LIMA - LIMA - SANTIAGO DE SURCO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20100182263',
                'business_name'  => 'MONTANA S.A.',
                'description'    => '',
                'address'        => 'AV. JAVIER PRADO ESTE NRO. 6210 INT. 401 URB. LA RIVIERA DE MONTERRICO II ETAPA LIMA - LIMA - LA MOLINA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '23423423423',
                'business_name'  => 'SEVIDON S.A.C.',
                'description'    => '',
                'address'        => 'LA COMUNIDAD - PAITA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20133417452',
                'business_name'  => 'AGROPECUARIA CHIMU S.R.L.',
                'description'    => '',
                'address'        => 'AV. CESAR VALLEJO NRO. 310',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20336183791',
                'business_name'  => 'EL PEDREGAL S.A.',
                'description'    => '',
                'address'        => 'CAR.MEDIO PIURA KM. 11.5 FND. CHAPAIRA Y TERELA (CARRETERA MEDIO PIURA KM. 11.5 - 12) PIURA - PIURA - CASTILLA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20505655215',
                'business_name'  => 'SAN CARLOS CONTRATISTAS GENERALES S.R.L',
                'description'    => '',
                'address'        => 'CAL.19 MZA. P2 LOTE. 06 URB. SANTO DOMINGO 6TA ETAPA (AL FINAL DE LA AV. CONDORCANQUI) LIMA - LIMA - CARABAYLLO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20100227542',
                'business_name'  => 'PROCESOS AGROINDUSTRIALES S.A.',
                'description'    => '',
                'address'        => 'CAL.AMADOR MERINO REYNA NRO. 267 INT. 1301 LIMA - LIMA - SAN ISIDRO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20608552171',
                'business_name'  => 'UNACEM PERU S.A.',
                'description'    => '',
                'address'        => 'AV. ATOCONGO NRO. 2440 (CARCA AL CAMPAMENTO DE UNACEM) LIMA - LIMA - VILLA MARIA DEL TRIUNFO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20471744493',
                'business_name'  => 'CALIZA CEMENTO INCA S.A.',
                'description'    => '',
                'address'        => 'LIMA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],

            [
                'person_type'    => 'NATURAL',
                'document_type'  => 'RUC',
                'document_number' => '12345678912',
                'business_name'  => 'MINEDU',
                'description'    => 'MINEDU',
                'address'        => 'LIMA',
                'contact_phone'  => '123456789',
                'contact_email'  => 'MINEDU@MINEDU.PE',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20601776309',
                'business_name'  => 'TRANSBAL EXPRESS S.A.C.',
                'description'    => '',
                'address'        => 'CAL. 25 DE DICIEMBRE MZA. H LOTE. 5 SEC. LAS PRADERAS - HUANCHACO - TRUJILLO',
                'contact_phone'  => '123456789',
                'contact_email'  => 'AAA@GMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20103117560',
                'business_name'  => 'EMP REG DE SERV PUB DE ELECT DL NORTE SA',
                'description'    => '',
                'address'        => 'CAL. SAN MARTIN NRO. 250, CERCADO DE CHICLAYO, CHICLAYO, CHICLAYO, LAMBAYEQUE, PERÚ',
                'contact_phone'  => '074481210',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'NO DOMICILIADO',
                'document_type'  => 'SIN DOCUMENTOS',
                'document_number' => '456756766',
                'business_name'  => 'DIRECCIÓN DE GESTIÓN DE RECURSOS EDUCATIVOS',
                'description'    => '',
                'address'        => 'CALLE DEL COMERCIO 193 - SAN BORJA - LIMA - LIMA - PERÚ',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20484004421',
                'business_name'  => 'GOBIERNO REGIONAL PIURA',
                'description'    => '',
                'address'        => 'AV. SAN RAMON NRO. S-N URB. SAN EDUARDO PIURA - PIURA - PIURA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20522473571',
                'business_name'  => 'EUROANDINO',
                'description'    => '',
                'address'        => 'JR. FERROCARRIL 127 PAITA - PAITA - PIURA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20178680049',
                'business_name'  => 'MUNICIPALIDAD PROVINCIAL DE MARISCAL CÁCERES',
                'description'    => 'COMPLETAR DATOS DE MUNICIPALIDAD',
                'address'        => 'JUANJUI',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20601705657',
                'business_name'  => 'ABASTECIMIENTOS INDUSTRIALES Y CORPORATIVOS E.I.R.L.',
                'description'    => '',
                'address'        => 'CAL. HUACARUNCO NRO. 147 DPTO. 301 - MARANGA ET. CUATRO - SAN MIGUEL - LIMA, PERÚ',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20398877544',
                'business_name'  => 'EMPREMAR E.I.R.L.',
                'description'    => '',
                'address'        => 'JR. SAN MARTIN NRO. 109 A.H. SAN MARTIN OCCIDENTE (ESPALDA DE EX COLEGIO LAS MERCEDES) PIURA - PAITA - PAITA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20601228514',
                'business_name'  => 'PULPAS Y PROCESADOS DEL AGRO SOCIEDAD ANONIMA-PULPAGRO',
                'description'    => '',
                'address'        => 'CAR.SULLANA - TAMBOGRANDE KM. 6.8 CAS. CIENEGUILLO CENTRO (CANAL CIENEGUILLO AL COSTADO DE AMBEV) PIURA - SULLANA - SULLANA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20466241734',
                'business_name'  => 'FLP DEL PERU SOCIEDAD ANONIMA CERRADA',
                'description'    => '',
                'address'        => 'CAR. SULLANA - TAMBOGRANDE KM. 1040 CAS. SAN VICENTE DE HUANGALA (AL COSTADO DE EMPRESA LIMONES PIURANOS)',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20603658265',
                'business_name'  => 'ENVASES PLASTICOS DEL NORTE S.A.C.',
                'description'    => '',
                'address'        => 'CAR.TAMBO GRANDE KM. 19 CAS. SAN VICENTE PIURA - PIURA - CASTILLA',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20109085660',
                'business_name'  => 'FEIMI E.I.R.L.',
                'description'    => 'FABRICACION DE PRODUCTOS METALICOS DE USO ESTRUCTURAL',
                'address'        => 'JR. LOS HUANCHOS NRO. 851, ZARATE, SAN JUAN DE LURIGANCHO, LIMA, LIMA, PERÚ',
                'contact_phone'  => '',
                'contact_email'  => 'FEIMI20@HOTMAIL.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20606116111',
                'business_name'  => 'MEDLOG PIURA SAC',
                'description'    => '',
                'address'        => 'PARQUE INDUSTRIAL PIURA FUTURA (PAN.NORTE-AUTOPISTA DEL SOL) PIURA - PIURA - VEINTISEIS DE OCTUBRE',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number' => '20305875539',
                'business_name'  => 'OLYMPIC PERU INC SUCURSAL DEL PERU',
                'description'    => '',
                'address'        => 'AV. RICARDO RIVERA NAVARRETE NRO. 475 DPTO. 1002 INT. C URB. JARDIN (TORRE NAVARRETE) LIMA - LIMA - SAN ISIDRO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number'=> '20528401393',
                'business_name'  => 'TAMSHI S.A.C.',
                'description'    => '',
                'address'        => 'IQUITOS, MAYNAS, LORETO, PERU',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number'=> '20100039207',
                'business_name'  => 'RANSA COMERCIAL S.A.C.',
                'description'    => '',
                'address'        => 'AV. ARGENTINA NRO. 2833 Z.I. INDUSTRIAL PROV. CONST. DEL CALLAO - PROV. CONST. DEL CALLAO - CALLAO',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number'=> '20610155341',
                'business_name'  => 'CONSORCIO AYESA- HMV',
                'description'    => '',
                'address'        => 'AV. ENRIQUE CANAVAL Y MOREYRA NRO. 480 INT. 901',
                'contact_phone'  => '',
                'contact_email'  => 'LYAKSETIG@AYESA.COM',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number'=> '20610153551',
                'business_name'  => 'SEED FOOD S.A.C.',
                'description'    => '',
                'address'        => 'AV. JAVIER PRADO ESTE 175, INTERIOR 1304. URB. FUNDO CONDE DE SAN ISIDRO, SAN ISIDRO - LIMA.',
                'contact_phone'  => '',
                'contact_email'  => '',
                'logo'           => null,
            ],
            [
                'person_type'    => 'JURIDICA',
                'document_type'  => 'RUC',
                'document_number'=> '20608300393',
                'business_name'  => 'COMPAÑIA FOOD RETAIL S.A.C.',
                'description'    => '',
                'address'        => 'Cal. Cesar Morelli Nro. 181 - San Borja Norte (Piso 3) - Lima, Perú',
                'contact_phone'  => '01 620 3000',
                'contact_email'  => 'servicioalcliente@spsa.pe',
                'logo'           => null,
            ],
            // Puedes seguir agregando más clientes aquí si tienes más datos
        ];

        foreach ($clients as $client) {
            Client::create($client);
        }
    }
}
