<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pricelist;
use App\Models\Unit;
use App\Models\PriceType;

class PricelistCorrectivoBTSeeder2 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener el tipo de precio "Mantenimiento Correctivos Baja Tensión"
        $priceType = PriceType::firstOrCreate(['name' => 'Mantenimiento Correctivos Baja Tensión']);

        // Datos de Mantenimiento Correctivos Baja Tensión - Parte 2
        $pricelists = [
            ['sat_line' => 'MCBT151', 'sat_description' => 'ANGULO INTERNO DE 20 X 12.5 MM EFAPHEL', 'unit' => 'UNIDAD', 'unit_price' => 3.00],
            ['sat_line' => 'MCBT152', 'sat_description' => 'ANGULO INTERNO DE 50 X 20 MM LEGRAND DLP-S 638161', 'unit' => 'UNIDAD', 'unit_price' => 6.00],
            ['sat_line' => 'MCBT153', 'sat_description' => 'ANGULO PLANO DE 110 X 50 MM 10093RBR EFAPEL', 'unit' => 'UNIDAD', 'unit_price' => 11.00],
            ['sat_line' => 'MCBT154', 'sat_description' => 'ANGULO PLANO DE 20 X 12.5 MM EFAPHEL', 'unit' => 'UNIDAD', 'unit_price' => 6.46],
            ['sat_line' => 'MCBT155', 'sat_description' => 'ANGULO PLANO DE 50 X 20 MM LEGRAND 638163', 'unit' => 'UNIDAD', 'unit_price' => 7.38],
            ['sat_line' => 'MCBT156', 'sat_description' => 'APLICACIÓN DE DOSIS DE THOR GEL', 'unit' => 'UNIDAD', 'unit_price' => 119.42],
            ['sat_line' => 'MCBT157', 'sat_description' => 'ARRANCADOR SUAVE - SCHNEIDER - ATS22D17S6 - ATS22-CONT. 220V-POTENC. DE 230V (4KW)/400…440V (7,5KW)/500V (9KW)', 'unit' => 'UNIDAD', 'unit_price' => 2470.22],
            ['sat_line' => 'MCBT158', 'sat_description' => 'ARRANCADOR SUAVE - SCHNEIDER - ATS22D32Q - ATS22-CONTROL 220 V-POTENCIA 230 V (7,5 KW)/400…440 V (15 KW)', 'unit' => 'UNIDAD', 'unit_price' => 3841.79],
            ['sat_line' => 'MCBT159', 'sat_description' => 'BARRA DE COBRE PARA PUESTA A TIERRA AL INTERIOR DEL TABLERO ELÉCTRICO PARA 10 PUNTOS', 'unit' => 'UNIDAD', 'unit_price' => 119.40],
            ['sat_line' => 'MCBT160', 'sat_description' => 'BARRA DE COBRE PARA PUESTA A TIERRA AL INTERIOR DEL TABLERO ELÉCTRICO PARA 20 PUNTOS', 'unit' => 'UNIDAD', 'unit_price' => 122.50],
            ['sat_line' => 'MCBT161', 'sat_description' => 'BARRA DE COBRE PARA PUESTA A TIERRA AL INTERIOR DEL TABLERO ELÉCTRICO PARA 5 PUNTOS', 'unit' => 'UNIDAD', 'unit_price' => 39.50],
            ['sat_line' => 'MCBT162', 'sat_description' => 'BASE PARA PLACA 110X50 10971ABR EFAPEL', 'unit' => 'UNIDAD', 'unit_price' => 4.70],
            ['sat_line' => 'MCBT163', 'sat_description' => 'BORNERA PORTAFUSIBLE 0.25 - 6.0 MM2 (P/ FUSIBLE 5 X 20)   _ LEGRAND _ 37181', 'unit' => 'UNIDAD', 'unit_price' => 30.00],
            ['sat_line' => 'MCBT164', 'sat_description' => 'BORNERA REGLETA NEGRO NYBLOC _ LEGRAND _ 34211 _ 4 MM2', 'unit' => 'UNIDAD', 'unit_price' => 12.00],
            ['sat_line' => 'MCBT165', 'sat_description' => 'BORNERA REGLETA NEGRO NYBLOC _ LEGRAND _ 34213 _ 6 MM2', 'unit' => 'UNIDAD', 'unit_price' => 12.00],
            ['sat_line' => 'MCBT166', 'sat_description' => 'BORNERA REGLETA NEGRO NYBLOC _ LEGRAND _ 34215 _ 10 MM2', 'unit' => 'UNIDAD', 'unit_price' => 25.95],
            ['sat_line' => 'MCBT167', 'sat_description' => 'BORNERA REGLETA NEGRO NYBLOC _ LEGRAND _ 34217 _ 16 MM2', 'unit' => 'UNIDAD', 'unit_price' => 37.83],
            ['sat_line' => 'MCBT168', 'sat_description' => 'BORNERA TOMA A TIERRA DE 16 MM2 (4.0 - 16 MM2) _ LEGRAND _ 37174', 'unit' => 'UNIDAD', 'unit_price' => 29.00],
            ['sat_line' => 'MCBT169', 'sat_description' => 'BORNERAS P/ RIEL DIN _ LEGRAND _ 16 MM2 (6 AWG)', 'unit' => 'UNIDAD', 'unit_price' => 11.00],
            ['sat_line' => 'MCBT170', 'sat_description' => 'BORNERAS P/ RIEL DIN _ LEGRAND _ 2.5 MM2 (14 AWG)', 'unit' => 'UNIDAD', 'unit_price' => 4.00],
            ['sat_line' => 'MCBT171', 'sat_description' => 'BORNERAS P/ RIEL DIN _ LEGRAND _ 4 MM2 (12 AWG)', 'unit' => 'UNIDAD', 'unit_price' => 4.00],
            ['sat_line' => 'MCBT172', 'sat_description' => 'BORNERAS P/ RIEL DIN _ LEGRAND _ 6 MM2 (10 AWG)', 'unit' => 'UNIDAD', 'unit_price' => 4.80],
            ['sat_line' => 'MCBT173', 'sat_description' => 'CABLE _ BELDEN _ UTP _ CATERGORÍA 5E', 'unit' => 'M', 'unit_price' => 3.00],
            ['sat_line' => 'MCBT174', 'sat_description' => 'CABLE APANTALLADO _ BELDEN _ 2X2X22AWG', 'unit' => 'ML', 'unit_price' => 12.52],
            ['sat_line' => 'MCBT175', 'sat_description' => 'CABLE DE COBRE DESNUDO SUAVE _ INDECO _ 16 MM2 (7 HILOS)', 'unit' => 'M', 'unit_price' => 13.00],
            ['sat_line' => 'MCBT176', 'sat_description' => 'CABLE DE COBRE DESNUDO SUAVE _ INDECO _ 25 MM2 (7 HILOS)', 'unit' => 'M', 'unit_price' => 18.00],
            ['sat_line' => 'MCBT177', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO)  _ INDECO _ N2XOH80 _ 120 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 78.00],
            ['sat_line' => 'MCBT178', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO)  _ INDECO _ N2XOH80 _ 150 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 83.00],
            ['sat_line' => 'MCBT179', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO)  _ INDECO _ N2XOH80 _ 185 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 104.86],
            ['sat_line' => 'MCBT180', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO)  _ INDECO _ N2XOH80 _ 240 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 136.00],
            ['sat_line' => 'MCBT181', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO)  _ INDECO _ NH80 _ 10 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 6.00],
            ['sat_line' => 'MCBT182', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO)  _ INDECO _ NH80 _ 70 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 41.72],
            ['sat_line' => 'MCBT183', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO)  _ INDECO _ NH80 _ 95 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 56.00],
            ['sat_line' => 'MCBT184', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO) _ INDECO _ NH80 _ 1.5 MM2 - 750 V', 'unit' => 'ML', 'unit_price' => 1.53],
            ['sat_line' => 'MCBT185', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO) _ INDECO _ NH80 _ 16 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 10.11],
            ['sat_line' => 'MCBT186', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO) _ INDECO _ NH80 _ 2.5 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 1.48],
            ['sat_line' => 'MCBT187', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO) _ INDECO _ NH80 _ 25 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 15.43],
            ['sat_line' => 'MCBT188', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO) _ INDECO _ NH80 _ 35 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 21.84],
            ['sat_line' => 'MCBT189', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO) _ INDECO _ NH80 _ 4 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 3.79],
            ['sat_line' => 'MCBT190', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO) _ INDECO _ NH80 _ 50 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 29.26],
            ['sat_line' => 'MCBT191', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO) _ INDECO _ NH80 _ 6 MM2 - 750 V', 'unit' => 'M', 'unit_price' => 5.18],
            ['sat_line' => 'MCBT192', 'sat_description' => 'CABLE ELECTRICO (LIBRE DE HALOGENO) _ INDECO _ NH80 _ 6MM2 - 750 V', 'unit' => 'M', 'unit_price' => 5.18],
            ['sat_line' => 'MCBT193', 'sat_description' => 'CABLE ELECTRICO _ ELCOPE _ CPT _ 10 MM2 (8 AWG) - (AMARILLO/VERDE)', 'unit' => 'M', 'unit_price' => 5.20],
            ['sat_line' => 'MCBT194', 'sat_description' => 'CABLE ELECTRICO _ ELCOPE _ CPT _ 120 MM2 (2 AWG) - (AMARILLO/VERDE)', 'unit' => 'M', 'unit_price' => 65.80],
            ['sat_line' => 'MCBT195', 'sat_description' => 'CABLE ELECTRICO _ ELCOPE _ CPT _ 16 MM2  (6 AWG) - (AMARILLO/VERDE)', 'unit' => 'M', 'unit_price' => 8.00],
            ['sat_line' => 'MCBT196', 'sat_description' => 'CABLE ELECTRICO _ ELCOPE _ CPT _ 2.5 MM2 ( 14 AWG) - (AMARILLO/VERDE)', 'unit' => 'M', 'unit_price' => 1.60],
            ['sat_line' => 'MCBT197', 'sat_description' => 'CABLE ELECTRICO _ ELCOPE _ CPT _ 25 MM2 (4 AWG) - (AMARILLO/VERDE)', 'unit' => 'M', 'unit_price' => 14.00],
            ['sat_line' => 'MCBT198', 'sat_description' => 'CABLE ELECTRICO _ ELCOPE _ CPT _ 35 MM2 (2 AWG) - (AMARILLO/VERDE)', 'unit' => 'M', 'unit_price' => 19.00],
            ['sat_line' => 'MCBT199', 'sat_description' => 'CABLE ELECTRICO _ ELCOPE _ CPT _ 4 MM2 ( 12 AWG) - (AMARILLO/VERDE)', 'unit' => 'M', 'unit_price' => 3.00],
            ['sat_line' => 'MCBT200', 'sat_description' => 'CABLE ELECTRICO _ ELCOPE _ CPT _ 6 MM2 (10 AWG) - (AMARILLO/VERDE)', 'unit' => 'M', 'unit_price' => 4.00],
            ['sat_line' => 'MCBT201', 'sat_description' => 'CABLE ELECTRICO _ ELCOPE _ CPT _ 70 MM2 (2 AWG) - (AMARILLO/VERDE)', 'unit' => 'M', 'unit_price' => 39.50],
            ['sat_line' => 'MCBT202', 'sat_description' => 'CABLE ELECTRICO _ ELCOPE _ CPT _ 95 MM2 (2 AWG) - (AMARILLO/VERDE)', 'unit' => 'M', 'unit_price' => 54.50],
            ['sat_line' => 'MCBT203', 'sat_description' => 'CABLE N2XSY 1X120MM2 18/30KV', 'unit' => 'M', 'unit_price' => 94.00],
            ['sat_line' => 'MCBT204', 'sat_description' => 'CABLE N2XSY 1X50MM2 18/30KV', 'unit' => 'M', 'unit_price' => 52.20],
            ['sat_line' => 'MCBT205', 'sat_description' => 'CABLE N2XSY 1X70MM2 18/30KV', 'unit' => 'M', 'unit_price' => 73.89],
            ['sat_line' => 'MCBT206', 'sat_description' => 'CABLE N2XSY 1X95MM2 18/30KV', 'unit' => 'M', 'unit_price' => 92.00],
            ['sat_line' => 'MCBT207', 'sat_description' => 'CABLE VULCANIZADO (FREETOX) _ INDECO _ NH _ 3X2.5 MM2', 'unit' => 'M', 'unit_price' => 8.00],
            ['sat_line' => 'MCBT208', 'sat_description' => 'CABLE VULCANIZADO (FREETOX) _ INDECO _ NH _ 3X4 MM2', 'unit' => 'M', 'unit_price' => 10.00],
            ['sat_line' => 'MCBT209', 'sat_description' => 'CABLE VULCANIZADO NH 7G, (7X2.5 MM2)', 'unit' => 'M', 'unit_price' => 25.32],
            ['sat_line' => 'MCBT210', 'sat_description' => 'CAJA CONDUIT RECTANGULAR RR(C) 1 1/2´ DE 4 SALIDAS C/ OREJAS - S/ TAPA RR-0471-M _ RAWELT', 'unit' => 'UNIDAD', 'unit_price' => 27.10],
            ['sat_line' => 'MCBT211', 'sat_description' => 'CAJA CONDUIT RECTANGULAR RR(C) 1/2 DE 4 SALIDAS C/ OREJAS - S/ TAPA RR-0471-M _ RAWELT', 'unit' => 'UNIDAD', 'unit_price' => 16.03],
            ['sat_line' => 'MCBT212', 'sat_description' => 'CAJA CONDUIT RECTANGULAR RR(C) 1´ DE 4 SALIDAS C/ OREJAS - S/ TAPA RR-0471-M _ RAWELT', 'unit' => 'UNIDAD', 'unit_price' => 18.99],
            ['sat_line' => 'MCBT213', 'sat_description' => 'CAJA CONDUIT RECTANGULAR RR(C) 3/4 DE 4 SALIDAS C/ OREJAS - S/ TAPA RR-0471-M _ RAWELT', 'unit' => 'UNIDAD', 'unit_price' => 14.97],
            ['sat_line' => 'MCBT214', 'sat_description' => 'CAJA DE DERIVACIÓN (ADOSABLE) _ TICINO _CAJA DE PASE PVC DE 108 X 108 X 64 MM, PARA TOMACORRIENTE O INTERRUPTOR', 'unit' => 'UNIDAD', 'unit_price' => 12.86],
            ['sat_line' => 'MCBT215', 'sat_description' => 'CAJA DE DERIVACIÓN (ADOSABLE) _10"X 10" - METALICA', 'unit' => 'UNIDAD', 'unit_price' => 37.00],
            ['sat_line' => 'MCBT216', 'sat_description' => 'CAJA DE DERIVACIÓN (ADOSABLE) _10"X 10" DE PVC', 'unit' => 'UNIDAD', 'unit_price' => 19.00],
            ['sat_line' => 'MCBT217', 'sat_description' => 'CAJA DE DERIVACIÓN (ADOSABLE) _4"X 2" DE PVC', 'unit' => 'UNIDAD', 'unit_price' => 8.70],
            ['sat_line' => 'MCBT218', 'sat_description' => 'CAJA DE DERIVACIÓN (ADOSABLE) _4"X 4" - METALICA', 'unit' => 'UNIDAD', 'unit_price' => 11.00],
            ['sat_line' => 'MCBT219', 'sat_description' => 'CAJA DE DERIVACIÓN (ADOSABLE) _4"X 4" DE PVC', 'unit' => 'UNIDAD', 'unit_price' => 10.00],
            ['sat_line' => 'MCBT220', 'sat_description' => 'CAJA DE DERIVACIÓN (ADOSABLE) _6"X 6" - METALICA', 'unit' => 'UNIDAD', 'unit_price' => 12.00],
            ['sat_line' => 'MCBT221', 'sat_description' => 'CAJA DE DERIVACIÓN (ADOSABLE) _6"X 6" DE PVC', 'unit' => 'UNIDAD', 'unit_price' => 13.00],
            ['sat_line' => 'MCBT222', 'sat_description' => 'CAJA DE DERIVACIÓN (ADOSABLE) _8"X 8" - METALICA', 'unit' => 'UNIDAD', 'unit_price' => 31.30],
            ['sat_line' => 'MCBT223', 'sat_description' => 'CAJA DE DERIVACIÓN (ADOSABLE) _8"X 8" DE PVC', 'unit' => 'UNIDAD', 'unit_price' => 18.04],
            ['sat_line' => 'MCBT224', 'sat_description' => 'CAJA DE DERIVACIÓN (EMPOTRABLE) _ 6"X 6"X 4" (15 X 15 X 10 CM) 1/20 - METALICA', 'unit' => 'UNIDAD', 'unit_price' => 18.50],
            ['sat_line' => 'MCBT225', 'sat_description' => 'CAJA DE REGISTRO DE CONCRETO (CON TAPA) PARA POZO A TIERRA', 'unit' => 'UNIDAD', 'unit_price' => 44.00],
            ['sat_line' => 'MCBT226', 'sat_description' => 'CAJA HIDROBOX KID COMPLETO 2 DADOS INTERRUPTORE MÁS DADO CIEGO', 'unit' => 'UNIDAD', 'unit_price' => 84.84],
            ['sat_line' => 'MCBT227', 'sat_description' => 'CAJA HIDROBOX KID COMPLETO 2 DADOS TOMACORRIENTES CON PUESTA A TIERRA MÁS DADO CIEGO', 'unit' => 'UNIDAD', 'unit_price' => 114.24],
            ['sat_line' => 'MCBT228', 'sat_description' => 'CANALETA DE 110 X 50MM X 2MTS EFAPEL', 'unit' => 'UNIDAD', 'unit_price' => 52.32],
            ['sat_line' => 'MCBT229', 'sat_description' => 'CANALETA DE 20 X 12.5 MM EFAPHEL', 'unit' => 'ML', 'unit_price' => 11.53],
            ['sat_line' => 'MCBT230', 'sat_description' => 'CANALETA DE 50 X 20 MM 2 COMP LEGRAND DLP-S 638168', 'unit' => 'UNIDAD', 'unit_price' => 19.00],
            ['sat_line' => 'MCBT231', 'sat_description' => 'CANALETA INDUSTRIAL _ LEGRAND _ 36200 _ 25 X 25 MM - LINA 25 RANURADA', 'unit' => 'ML', 'unit_price' => 32.00],
            ['sat_line' => 'MCBT232', 'sat_description' => 'CANALETA INDUSTRIAL _ LEGRAND _ 36201 _ 25 X 40 MM - LINA 25 RANURADA', 'unit' => 'ML', 'unit_price' => 36.75],
            ['sat_line' => 'MCBT233', 'sat_description' => 'CANALETA INDUSTRIAL _ LEGRAND _ 36202 _ 25 X 60 MM - LINA 25 RANURADA', 'unit' => 'ML', 'unit_price' => 40.00],
            ['sat_line' => 'MCBT234', 'sat_description' => 'CANALETA INDUSTRIAL _ LEGRAND _ 36205 _ 40 X 25 MM - LINA 25 RANURADA', 'unit' => 'ML', 'unit_price' => 40.00],
            ['sat_line' => 'MCBT235', 'sat_description' => 'CANALETA INDUSTRIAL _ LEGRAND _ 36213 _ 60 X 80 MM - LINA 25 RANURADA', 'unit' => 'ML', 'unit_price' => 49.00],
            ['sat_line' => 'MCBT236', 'sat_description' => 'CANALETA INDUSTRIAL _ LEGRAND _ 36216 _ 80 X 60 MM - LINA 25 RANURADA', 'unit' => 'ML', 'unit_price' => 75.80],
            ['sat_line' => 'MCBT237', 'sat_description' => 'CHAPAS TIPO LENGÜETA PARA TABLERO ELÉCTRICO', 'unit' => 'UNIDAD', 'unit_price' => 15.00],
            ['sat_line' => 'MCBT238', 'sat_description' => 'CHAPAS TIPO MANIJA PARA TABLERO ELÉCTRICO', 'unit' => 'UNIDAD', 'unit_price' => 13.31],
            ['sat_line' => 'MCBT239', 'sat_description' => 'CHAPAS TIPO PLUSH PARA TABLERO ELÉCTRICO', 'unit' => 'UNIDAD', 'unit_price' => 12.00],
            ['sat_line' => 'MCBT240', 'sat_description' => 'COMPUTER SMART III 6, REGULADOR ENERGÍA REACTIVA TRIFÁSICO. REGULACIÓN, MEDIDA, CONTROL DE FUGAS Y COMUNICACIONES - CIRCUTOR-R13851', 'unit' => 'UNIDAD', 'unit_price' => 1427.00],
            ['sat_line' => 'MCBT241', 'sat_description' => 'CONDENSADORES TUBULARES TRIFÁSICOS (SERIE ULTRA HEAVY DUTY) 12KVAR - CIRCUTOR-R2HM26', 'unit' => 'UNIDAD', 'unit_price' => 281.00],
            ['sat_line' => 'MCBT242', 'sat_description' => 'CONDESADOR TRIFÁSICO DE POTENCIA VARPLUS 25 KVAR', 'unit' => 'UNIDAD', 'unit_price' => 608.00],
            ['sat_line' => 'MCBT243', 'sat_description' => 'CONECTOR _ 1 1/2" EMT', 'unit' => 'UNIDAD', 'unit_price' => 3.67],
            ['sat_line' => 'MCBT244', 'sat_description' => 'CONECTOR _ 1" EMT', 'unit' => 'UNIDAD', 'unit_price' => 2.25],
            ['sat_line' => 'MCBT245', 'sat_description' => 'CONECTOR _ 2" EMT', 'unit' => 'UNIDAD', 'unit_price' => 4.71],
            ['sat_line' => 'MCBT246', 'sat_description' => 'CONECTOR _ 3" EMT', 'unit' => 'UNIDAD', 'unit_price' => 25.57],
            ['sat_line' => 'MCBT247', 'sat_description' => 'CONECTOR _ 4" EMT', 'unit' => 'UNIDAD', 'unit_price' => 33.65],
            ['sat_line' => 'MCBT248', 'sat_description' => 'CONECTOR A CAJA DE PVC (LUZ) SAP _ 1 1/2"', 'unit' => 'UNIDAD', 'unit_price' => 1.00],
            ['sat_line' => 'MCBT249', 'sat_description' => 'CONECTOR A CAJA DE PVC (LUZ) SAP _ 1"', 'unit' => 'UNIDAD', 'unit_price' => 0.88],
            ['sat_line' => 'MCBT250', 'sat_description' => 'CONECTOR A CAJA DE PVC (LUZ) SAP _ 1/2"', 'unit' => 'UNIDAD', 'unit_price' => 0.88],
            ['sat_line' => 'MCBT251', 'sat_description' => 'CONECTOR A CAJA DE PVC (LUZ) SAP _ 2"', 'unit' => 'UNIDAD', 'unit_price' => 1.73],
            ['sat_line' => 'MCBT252', 'sat_description' => 'CONECTOR A CAJA DE PVC (LUZ) SAP _ 3/4"', 'unit' => 'UNIDAD', 'unit_price' => 0.88],
            ['sat_line' => 'MCBT253', 'sat_description' => 'CONECTOR A CAJA DE PVC (LUZ) SAP _ 4"', 'unit' => 'UNIDAD', 'unit_price' => 6.81],
            ['sat_line' => 'MCBT254', 'sat_description' => 'CONECTOR CURVO (LIQUID TIGHT) _ 1 1/2"', 'unit' => 'UNIDAD', 'unit_price' => 13.57],
            ['sat_line' => 'MCBT255', 'sat_description' => 'CONECTOR CURVO (LIQUID TIGHT) _ 1"', 'unit' => 'UNIDAD', 'unit_price' => 6.29],
            ['sat_line' => 'MCBT256', 'sat_description' => 'CONECTOR CURVO (LIQUID TIGHT) _ 2"', 'unit' => 'UNIDAD', 'unit_price' => 22.95],
            ['sat_line' => 'MCBT257', 'sat_description' => 'CONECTOR CURVO (LIQUID TIGHT) _ 3/4"', 'unit' => 'UNIDAD', 'unit_price' => 4.11],
            ['sat_line' => 'MCBT258', 'sat_description' => 'CONECTOR DE BRONCE AB (PARA VARILLA) _ 3/4"', 'unit' => 'UNIDAD', 'unit_price' => 9.90],
            ['sat_line' => 'MCBT259', 'sat_description' => 'CONECTOR DE BRONCE AB (PARA VARILLA) _ 5/8"', 'unit' => 'UNIDAD', 'unit_price' => 7.84],
            ['sat_line' => 'MCBT260', 'sat_description' => 'CONECTOR RECTO (HERMETICO CONDUIT) _ 1 1/2"', 'unit' => 'UNIDAD', 'unit_price' => 8.40],
            ['sat_line' => 'MCBT261', 'sat_description' => 'CONECTOR RECTO (HERMETICO CONDUIT) _ 1"', 'unit' => 'UNIDAD', 'unit_price' => 4.90],
            ['sat_line' => 'MCBT262', 'sat_description' => 'CONECTOR RECTO (HERMETICO CONDUIT) _ 2"', 'unit' => 'UNIDAD', 'unit_price' => 15.85],
            ['sat_line' => 'MCBT263', 'sat_description' => 'CONECTOR RECTO (HERMETICO CONDUIT) _ 3/4"', 'unit' => 'UNIDAD', 'unit_price' => 3.76],
            ['sat_line' => 'MCBT264', 'sat_description' => 'CONMUTADOR MANUAL TRIFASICO DE 160 A _ BREMAS (CON ACCESORIOS COMPLETOS INTERNOS Y EXTERNOS)', 'unit' => 'UNIDAD', 'unit_price' => 1646.47],
            ['sat_line' => 'MCBT265', 'sat_description' => 'CONMUTADOR ROTATIVO _ BREMAS _ (1 - 0 - 2) DE 32 A', 'unit' => 'UNIDAD', 'unit_price' => 145.00],
            ['sat_line' => 'MCBT266', 'sat_description' => 'CONMUTADOR ROTATIVO _ BREMAS _ (1 - 0 - 2) DE 50 A', 'unit' => 'UNIDAD', 'unit_price' => 275.00],
            ['sat_line' => 'MCBT267', 'sat_description' => 'CONTACTOR - TESYS D - SCHENEIDER - 220V - 25A - 3P (2NO/1NC) - AC3', 'unit' => 'UNIDAD', 'unit_price' => 283.00],
            ['sat_line' => 'MCBT268', 'sat_description' => 'CONTACTOR - TESYS D - SCHNEIDER - 220V - 18A - 3P(3 NO) - AC-3', 'unit' => 'UNIDAD', 'unit_price' => 189.40],
            ['sat_line' => 'MCBT269', 'sat_description' => 'CONTACTOR - TESYS GC - SCHNEIDER - 25 A - 2 NO + 2 NC - 220...240 VAC', 'unit' => 'UNIDAD', 'unit_price' => 340.50],
            ['sat_line' => 'MCBT270', 'sat_description' => 'CONTACTOR _ SCHENEIDER _ 220V _ 32A 3P / AC3', 'unit' => 'UNIDAD', 'unit_price' => 379.24],
            ['sat_line' => 'MCBT271', 'sat_description' => 'CONTACTOR _ SCHENEIDER _ 220V _ 40A 3P / AC3', 'unit' => 'UNIDAD', 'unit_price' => 435.09],
            ['sat_line' => 'MCBT272', 'sat_description' => 'CONTACTOR _ SCHENEIDER _ 220V _ 50A 3P / AC3', 'unit' => 'UNIDAD', 'unit_price' => 561.06],
            ['sat_line' => 'MCBT273', 'sat_description' => 'CONTACTOR _ SCHENEIDER _ 220V _ 65A 3P / AC3', 'unit' => 'UNIDAD', 'unit_price' => 627.33],
            ['sat_line' => 'MCBT274', 'sat_description' => 'CONTACTOR _ SCHENEIDER _ 220V _ 9A 3P / AC3', 'unit' => 'UNIDAD', 'unit_price' => 122.80],
            ['sat_line' => 'MCBT275', 'sat_description' => 'CONTACTOR BIPOLAR_ SCHNEIDER _ 220V _ 25 A', 'unit' => 'UNIDAD', 'unit_price' => 107.87],
            ['sat_line' => 'MCBT276', 'sat_description' => 'CONTACTOR DE POTENCIA, 3 AC 50 A CIRCUTOR - CMC-150B', 'unit' => 'UNIDAD', 'unit_price' => 0.00],
            ['sat_line' => 'MCBT277', 'sat_description' => 'CONTACTOR PARA CONDESADOR 15/25/36KVAR 220/440/690  LC1DTKM7 - SCHNEIDER ELECTRIC', 'unit' => 'UNIDAD', 'unit_price' => 402.00],
            ['sat_line' => 'MCBT278', 'sat_description' => 'CONTACTOR TRIPOLAR_ SCHNEIDER _ 220V _ 115A /AC3', 'unit' => 'UNIDAD', 'unit_price' => 0.00],
            ['sat_line' => 'MCBT279', 'sat_description' => 'CONTACTOR TRIPOLAR_ SCHNEIDER _ 220V _ 150A /AC3', 'unit' => 'UNIDAD', 'unit_price' => 0.00],
            ['sat_line' => 'MCBT280', 'sat_description' => 'CONTACTOR TRIPOLAR_ SCHNEIDER _ 220V _ 250A/ AC4', 'unit' => 'UNIDAD', 'unit_price' => 5072.94],
            ['sat_line' => 'MCBT281', 'sat_description' => 'CURVA  _ 1 1/2" EMT', 'unit' => 'UNIDAD', 'unit_price' => 6.50],
            ['sat_line' => 'MCBT282', 'sat_description' => 'CURVA  _ 2" EMT', 'unit' => 'UNIDAD', 'unit_price' => 9.00],
            ['sat_line' => 'MCBT283', 'sat_description' => 'CURVA  _ 3" EMT', 'unit' => 'UNIDAD', 'unit_price' => 29.70],
            ['sat_line' => 'MCBT284', 'sat_description' => 'CURVA  _ 4" EMT', 'unit' => 'UNIDAD', 'unit_price' => 67.20],
            ['sat_line' => 'MCBT285', 'sat_description' => 'CURVA _ 1" EMT', 'unit' => 'UNIDAD', 'unit_price' => 3.00],
            ['sat_line' => 'MCBT286', 'sat_description' => 'CURVA _ 3/4" EMT', 'unit' => 'UNIDAD', 'unit_price' => 1.50],
            ['sat_line' => 'MCBT287', 'sat_description' => 'CURVA DE PVC (LUZ) SAP _ 1 1/2"', 'unit' => 'UNIDAD', 'unit_price' => 5.00],
            ['sat_line' => 'MCBT288', 'sat_description' => 'CURVA DE PVC (LUZ) SAP _ 1"', 'unit' => 'UNIDAD', 'unit_price' => 1.95],
            ['sat_line' => 'MCBT289', 'sat_description' => 'CURVA DE PVC (LUZ) SAP _ 2"', 'unit' => 'UNIDAD', 'unit_price' => 7.30],
            ['sat_line' => 'MCBT290', 'sat_description' => 'CURVA DE PVC (LUZ) SAP _ 3"', 'unit' => 'UNIDAD', 'unit_price' => 19.00],
            ['sat_line' => 'MCBT291', 'sat_description' => 'CURVA DE PVC (LUZ) SAP _ 3/4"', 'unit' => 'UNIDAD', 'unit_price' => 1.20],
            ['sat_line' => 'MCBT292', 'sat_description' => 'CURVA DE PVC (LUZ) SAP _ 4"', 'unit' => 'UNIDAD', 'unit_price' => 32.00],
            ['sat_line' => 'MCBT293', 'sat_description' => 'DADO CIEGO _ TICINO _ 5000/9', 'unit' => 'UNIDAD', 'unit_price' => 5.88],
            ['sat_line' => 'MCBT294', 'sat_description' => 'DADO INTERRUPTOR _ TICINO _ 5001 _ 16A - 250 VAC', 'unit' => 'UNIDAD', 'unit_price' => 19.00],
            ['sat_line' => 'MCBT295', 'sat_description' => 'DADO INTERRUPTOR BIPOLAR _ TICINO _ 5011 _ 16 A - 250 VAC', 'unit' => 'UNIDAD', 'unit_price' => 41.40],
            ['sat_line' => 'MCBT296', 'sat_description' => 'DADO INTERRUPTOR DE 3 VIAS   _ TICINO _ 5003 _ 16 A - 250 VAC', 'unit' => 'UNIDAD', 'unit_price' => 18.10],
            ['sat_line' => 'MCBT297', 'sat_description' => 'DADO PULSADOR UNIPORLAR _ TICINO _ 5005 _ 10 A - 250 V', 'unit' => 'UNIDAD', 'unit_price' => 17.90],
            ['sat_line' => 'MCBT298', 'sat_description' => 'DADO TOMACORRIENTE AMERICANO 2P+T _ TICINO _ 5028 _ 15 A - 220 V', 'unit' => 'UNIDAD', 'unit_price' => 29.85],
            ['sat_line' => 'MCBT299', 'sat_description' => 'DADO TOMACORRIENTE UNIVERSAL _ TICINO _ 5025 _ 16 A - 250 V - (4 - 8) MM', 'unit' => 'UNIDAD', 'unit_price' => 28.00],
            ['sat_line' => 'MCBT300', 'sat_description' => 'DETECTOR DE HUMO ALAMBRICO', 'unit' => 'UNIDAD', 'unit_price' => 94.00],
        ];

        foreach ($pricelists as $item) {
            $unit = Unit::firstOrCreate(
                ['symbol' => $item['unit']],
                ['name' => $item['unit'], 'category' => 'SERVICIO']
            );

            Pricelist::create([
                'sat_line' => $item['sat_line'],
                'sat_description' => $item['sat_description'],
                'unit_id' => $unit->id,
                'unit_price' => $item['unit_price'],
                'price_type_id' => $priceType->id,
            ]);
        }
    }
}
