<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pricelist;
use App\Models\Unit;
use App\Models\PriceType;

class PricelistCorrectivoBTSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener el tipo de precio "Mantenimiento Correctivos Baja Tensión"
        $priceType = PriceType::firstOrCreate(['name' => 'Mantenimiento Correctivos Baja Tensión']);

        // Datos de Mantenimiento Correctivos Baja Tensión
        $pricelists = [
            ['sat_line' => 'MCBT01', 'sat_description' => 'ASISTENCIA TÉCNICA PARA EMERGENCIAS (SERVICIO PROFESIONAL PARA DIAGNÓSTICO Y SOLUCIONES PARCIALES INCLUYE LAS DERIVADAS DE VISITAS INDECI, OSINERGMIN Y DEFENSA CIVI,  DEBE CONTEMPLAR CONSUMIBLES MENORES).', 'unit' => 'UNIDAD', 'unit_price' => 324.18],
            ['sat_line' => 'MCBT02', 'sat_description' => 'ASISTENCIA TÉCNICA PARA EMERGENCIAS (SERVICIO PROFESIONAL PARA DIAGNÓSTICO Y SOLUCIONES PARCIALES INCLUYE LAS DERIVADAS DE VISITAS INDECI, OSINERGMIN Y DEFENSA CIVI,  DEBE CONTEMPLAR CONSUMIBLES MENORES).', 'unit' => 'DE 1 A 10 EVENTO / MES', 'unit_price' => 324.18],
            ['sat_line' => 'MCBT03', 'sat_description' => 'ASISTENCIA TÉCNICA PARA EMERGENCIAS (SERVICIO PROFESIONAL PARA DIAGNÓSTICO Y SOLUCIONES PARCIALES INCLUYE LAS DERIVADAS DE VISITAS INDECI, OSINERGMIN Y DEFENSA CIVI,  DEBE CONTEMPLAR CONSUMIBLES MENORES).', 'unit' => 'DE 11 A 20 EVENTOS/ MES', 'unit_price' => 324.18],
            ['sat_line' => 'MCBT04', 'sat_description' => 'ASISTENCIA TÉCNICA PARA EMERGENCIAS (SERVICIO PROFESIONAL PARA DIAGNÓSTICO Y SOLUCIONES PARCIALES INCLUYE LAS DERIVADAS DE VISITAS INDECI, OSINERGMIN Y DEFENSA CIVI,  DEBE CONTEMPLAR CONSUMIBLES MENORES).', 'unit' => 'DE 21 A 40 EVENTOS/ MES', 'unit_price' => 324.18],
            ['sat_line' => 'MCBT05', 'sat_description' => 'ACONDICIONAMIENTO DE TABLERO ELÉCTRICO (INCLUYE EL ORDENAMIENDO Y PEINADO DE TODOS LOS CABLES, MONTAJE Y/O AJUSTE DE TODOS LAS CONEXIONES EN LOS INTERRUPTORES, CINTILLOS, CINTA ESPIRAL, OTROS).', 'unit' => 'UNIDAD', 'unit_price' => 196.00],
            ['sat_line' => 'MCBT06', 'sat_description' => 'ACTUALIZACIÓN DE DIAGRAMA UNIFILAR DIGITAL SEGÚN ESTANDAR (ESTA LÍNEA SOLO APLICA PARA CASOS QUE ESTÉN FUERA DEL MANTENIMIENTO PREVENTIVO Y LAS OBSERVACIONES QUE DERIVEN DE ELLA)', 'unit' => 'UNIDAD', 'unit_price' => 32.00],
            ['sat_line' => 'MCBT07', 'sat_description' => 'ADOSAMIENTO DE TABLERO ELÉCTRICO (INCLUYE MATERIALES DE FIJACIÓN: PERNOS, ARANDELAS, OTROS).', 'unit' => 'UNIDAD', 'unit_price' => 93.00],
            ['sat_line' => 'MCBT08', 'sat_description' => 'ANÁLISIS FÍSICO QUÍMICO DE ACEITE DE TRANSFORMADOR (ESTÁ LÍNEA NO APLICA PARA LOS MANTENIMIENTOS PREVENTIVOS )', 'unit' => 'UNIDAD', 'unit_price' => 463.25],
            ['sat_line' => 'MCBT09', 'sat_description' => 'ANULACIÓN DE CIRCUITO ELÉCTRICO (INCLUYE DESCONEXIÓN Y RETIRO DE CABLES Y/O ITM. ESTA LÍNEA SE USARÁ EXCLUSIVAMENTE CUANDO SE SOLICITE LA ANULACIÓN DE UN CIRCUITO POR EL RETIRO DE UNA CARGA O BAJA DE ALGÚN ACTIVO.', 'unit' => 'UNIDAD', 'unit_price' => 204.00],
            ['sat_line' => 'MCBT10', 'sat_description' => 'ATERRAMIENTO DE EQUIPOS ELECTRICOS (GRUPOS ELECTRÓGENOS)  INCLUYE CABLE (MÁXIMO 1ML), TERMINALES Y ACCESORIOS DE SUJECCIÓN PARA CULMINAR EL TRABAJO', 'unit' => 'UNIDAD', 'unit_price' => 16.40],
            ['sat_line' => 'MCBT11', 'sat_description' => 'ATERRAMIENTO DE EQUIPOS ELECTRICOS (HVA, EXTRACTORES, VENTILADORES, BOMBAS,ETC)  INCLUYE CABLE (MÁXIMO 1ML), TERMINALES Y ACCESORIOS DE SUJECCIÓN PARA CULMINAR EL TRABAJO', 'unit' => 'UNIDAD', 'unit_price' => 16.40],
            ['sat_line' => 'MCBT12', 'sat_description' => 'ATERRAMIENTO DE TABLEROS ELECTRICOS INCLUYE CABLE (MÁXIMO 1ML), TERMINALES Y ACCESORIOS DE SUJECCIÓN PARA CULMINAR EL TRABAJO', 'unit' => 'UNIDAD', 'unit_price' => 16.40],
            ['sat_line' => 'MCBT13', 'sat_description' => 'CALADO DE MANDIL PARA ADICONAR PROTECIONES ELÉCTRICAS O DISPOSITIVOS.', 'unit' => 'UNIDAD', 'unit_price' => 39.00],
            ['sat_line' => 'MCBT14', 'sat_description' => 'CAMBIO DE CHAPA EN TABLERO ELÉCTRICO.', 'unit' => 'UNIDAD', 'unit_price' => 21.60],
            ['sat_line' => 'MCBT15', 'sat_description' => 'CAMBIO DE EMPAQUETADURAS ALTA Y BAJA TENSIÓN  EN AISLADORES', 'unit' => 'UNIDAD', 'unit_price' => 70.00],
            ['sat_line' => 'MCBT16', 'sat_description' => 'CAMBIO DE JEBE DE PUERTA (INCLUYE EL SUMINISTRO DEL JEBE)', 'unit' => 'UNIDAD', 'unit_price' => 36.00],
            ['sat_line' => 'MCBT17', 'sat_description' => 'CAMBIO DE VENTILADORES O REJILLAS DE VENTILACIÓN.', 'unit' => 'UNIDAD', 'unit_price' => 58.00],
            ['sat_line' => 'MCBT18', 'sat_description' => 'CAMBIO O INSTALACIÓN DE LUMINARIA EN SALA DE VENTAS (INCLUYE DESINTALACIÓN Y RECURSOS PARA TRABAJOS EN ALTURA)', 'unit' => 'UNIDAD', 'unit_price' => 58.00],
            ['sat_line' => 'MCBT19', 'sat_description' => 'CAMBIO O INSTALACIÓN DE LUMINARIA EN TRANSTIENDA (OFICINAS, SSHH (MAX 3.5MT) ALMACENES,PLAYA DE ESTACIONAMIENTO (MAXIMO 14 MT) ETC, INCLUYE DESINTALACIÓN Y RECURSOS PARA TRABAJOS EN ALTURA)', 'unit' => 'UNIDAD', 'unit_price' => 43.00],
            ['sat_line' => 'MCBT20', 'sat_description' => 'CAMBIO O INSTALACIÓN DE TOMACORRIENTE (PLACA + DADOS).', 'unit' => 'UNIDAD', 'unit_price' => 22.54],
            ['sat_line' => 'MCBT21', 'sat_description' => 'CIERRE Y COMPACTACIÓN DE ZANJA DE ACUERDO A NORMAS CON TIERRA CERNIDA Y COMPACTACIÓN POR CAPAS (A TODO COSTO).', 'unit' => 'M3', 'unit_price' => 41.00],
            ['sat_line' => 'MCBT22', 'sat_description' => 'COLOCACION DE MANGA TERMOCONTRAIBLE EN CIRCUITO ELÉCTRICO (CONTEMPLA LAS 2 O 3 FASES Y EL SUMINISTRO DEL MATERIAL)', 'unit' => 'UNIDAD', 'unit_price' => 24.31],
            ['sat_line' => 'MCBT23', 'sat_description' => 'CONEXIÓN Y FIJACIÓN DEL CABLE DE PAT A LA VARILLA DE COBRE (CON CONECTOR TIPO AB).', 'unit' => 'UNIDAD', 'unit_price' => 18.00],
            ['sat_line' => 'MCBT24', 'sat_description' => 'CONSTRUCCIÓN DE POZO A TIERRA (A TODO COSTO)', 'unit' => 'GLB', 'unit_price' => 938.00],
            ['sat_line' => 'MCBT25', 'sat_description' => 'CORTE DE LOSA DE CONCRETO Y/O PAVIMENTO.', 'unit' => 'ML', 'unit_price' => 22.00],
            ['sat_line' => 'MCBT26', 'sat_description' => 'DESMONTAJE Y POSTERIOR MONTAJE DE REFLECTOR (INCLUYE EL RETIRO Y/O MONTAJE DEL PASTORAL) EN POSTE DE ALUMBRADO (INCLUYE LA DESCONEXIÓN Y CONEXIÓN DE LOS EQUIPOS Y/O ELEMENTOS, INCLUYE RECURSOS PARA TRABAJOS EN ALTURA)', 'unit' => 'UNIDAD', 'unit_price' => 223.00],
            ['sat_line' => 'MCBT27', 'sat_description' => 'EMPALME CAB_ELEC  (3 FASES) DE 16 MM2 DE SECCIÓN CON SUMINISTRO DE KIT DE EMPALME.', 'unit' => 'UNIDAD', 'unit_price' => 113.81],
            ['sat_line' => 'MCBT28', 'sat_description' => 'EMPALME CAB_ELEC  (3 FASES) DE 25 A 50 MM2 DE SECCIÓN CON SUMINISTRO DE KIT DE EMPALME.', 'unit' => 'UNIDAD', 'unit_price' => 286.35],
            ['sat_line' => 'MCBT29', 'sat_description' => 'EMPALME CAB_ELEC  (3 FASES) DE 70 A 90 MM2 O MÁS DE SECCIÓN CON SUMINISTRO DE KIT DE EMPALME.', 'unit' => 'UNIDAD', 'unit_price' => 348.92],
            ['sat_line' => 'MCBT30', 'sat_description' => 'EMPALME CAB_ELEC  (3 FASES) DE 95 A 185 MM2 O MÁS DE SECCIÓN CON SUMINISTRO DE KIT DE EMPALME.', 'unit' => 'UNIDAD', 'unit_price' => 131.00],
            ['sat_line' => 'MCBT31', 'sat_description' => 'EXCAVACIÓN DE ZANJA', 'unit' => 'M3', 'unit_price' => 39.00],
            ['sat_line' => 'MCBT32', 'sat_description' => 'FIJACIÓN, ASEGURAMIENTO Y/O AJUSTE DE ACCESORIOS (TOMACORRIENTES, MANDILES DE TABLERO, PULSADOR DE EMERGENCIA, INTERRUPTORES). INCLUYE MATERIALES CONSUMIBLES', 'unit' => 'UNIDAD', 'unit_price' => 39.00],
            ['sat_line' => 'MCBT33', 'sat_description' => 'FIJACIÓN, ASEGURAMIENTO Y/O AJUSTE DE LUMINARIA (POR DESPRENDIMIENTO Y/O PELIGRO DE CAÍDA). INCLUYE MATERIALES CONSUMIBLES', 'unit' => 'UNIDAD', 'unit_price' => 36.23],
            ['sat_line' => 'MCBT34', 'sat_description' => 'IDENTIFICACIÓN DE CIRCUITO ELÉCTRICO (MONOFASICO O TRIFÁSICO)', 'unit' => 'UNIDAD', 'unit_price' => 32.49],
            ['sat_line' => 'MCBT35', 'sat_description' => 'IDENTIFICACIÓN DE POZO A TIERRA: PINTADO DE TAPA DE POZO Y DE SU CÓDIGO CORRESPONDIENTE (INCLUYE LOS MATERIALES CONSUMIBLES).', 'unit' => 'UNIDAD', 'unit_price' => 43.32],
            ['sat_line' => 'MCBT36', 'sat_description' => 'INSTALACIÓN DE BOBINA DE DISPARO EN ITM DE CAJA MOLDEABLE', 'unit' => 'UNIDAD', 'unit_price' => 69.00],
            ['sat_line' => 'MCBT37', 'sat_description' => 'INSTALACIÓN DE BORNERA (TIPO REGLETA, TIPO RIEL DIN, OTROS).', 'unit' => 'UNIDAD', 'unit_price' => 3.41],
            ['sat_line' => 'MCBT38', 'sat_description' => 'INSTALACIÓN DE CONTACTOR, TELERRUPTORES (HASTA 120 AMP.)', 'unit' => 'UNIDAD', 'unit_price' => 58.98],
            ['sat_line' => 'MCBT39', 'sat_description' => 'INST DISPOSIT DIFEREN (DE 63 A 100 AMP.)', 'unit' => 'UNIDAD', 'unit_price' => 65.80],
            ['sat_line' => 'MCBT40', 'sat_description' => 'INST DISPOSIT DIFEREN (HASTA 40 AMP.)', 'unit' => 'UNIDAD', 'unit_price' => 62.00],
            ['sat_line' => 'MCBT41', 'sat_description' => 'INST_ENCHUFE 2P+T EN INDUSTRIAL TIPO MENEKE O SIMILAR EN CABLE ELÉCTRICO DE 63 HASTA 125A', 'unit' => 'UNIDAD', 'unit_price' => 50.00],
            ['sat_line' => 'MCBT42', 'sat_description' => 'INST_ENCHUFE 2P+T INDUSTRIAL TIPO MENEKE O SIMILAR EN CABLE ELÉCTRICO. DE 16  HASTA 32A', 'unit' => 'UNIDAD', 'unit_price' => 53.90],
            ['sat_line' => 'MCBT43', 'sat_description' => 'INST_ENCHUFE 3P+T O 3P+N+T EN INDUSTRIAL TIPO MENEKE O SIMILAR EN CABLE ELÉCTRICO DE 63 HASTA 125A', 'unit' => 'UNIDAD', 'unit_price' => 53.90],
            ['sat_line' => 'MCBT44', 'sat_description' => 'INST_ENCHUFE 3P+T O 3P+N+T INDUSTRIAL TIPO MENEKE O SIMILAR EN CABLE ELÉCTRICO. DE 16  HASTA 32A', 'unit' => 'UNIDAD', 'unit_price' => 53.90],
            ['sat_line' => 'MCBT45', 'sat_description' => 'INST_ENCHUFE SIMPLE MONOFASICO EN CABLE ELÉCTRICO HASTA 16A', 'unit' => 'UNIDAD', 'unit_price' => 44.00],
            ['sat_line' => 'MCBT46', 'sat_description' => 'INST_ESTABILIZ_ DE TENSIÓN DE 3 A 6 KVA', 'unit' => 'UNIDAD', 'unit_price' => 103.54],
            ['sat_line' => 'MCBT47', 'sat_description' => 'INST_ESTABILIZ_ DE TENSIÓN DE 7 A 10 KVA', 'unit' => 'UNIDAD', 'unit_price' => 224.18],
            ['sat_line' => 'MCBT48', 'sat_description' => 'INST_ESTABILIZ_ FERRORESONANTE 3 A 6 KVA', 'unit' => 'UNIDAD', 'unit_price' => 324.18],
            ['sat_line' => 'MCBT49', 'sat_description' => 'INST_ESTABILIZ_ FERRORESONANTE 7 A 10 KVA', 'unit' => 'UNIDAD', 'unit_price' => 324.18],
            ['sat_line' => 'MCBT50', 'sat_description' => 'INSTALACIÓN DE FUSIBLE (INCLUYE DESINSTALACIÓN)', 'unit' => 'UNIDAD', 'unit_price' => 24.00],
            ['sat_line' => 'MCBT51', 'sat_description' => 'INST_ INTERRUP_SIMPLE/DOBLE/3 O 4 VÍAS (PLACA + DADOS).', 'unit' => 'UNIDAD', 'unit_price' => 23.66],
            ['sat_line' => 'MCBT52', 'sat_description' => 'INST_INTERRUP_TERMOMAG_ TIPO CAJA MOLDEADA  MAYOR A 120 HASTA 250A', 'unit' => 'UNIDAD', 'unit_price' => 23.66],
            ['sat_line' => 'MCBT53', 'sat_description' => 'INST_INTERRUP_TERMOMAG_ TIPO CAJA MOLDEADA MAYOR A 250 HASTA 500A', 'unit' => 'UNIDAD', 'unit_price' => 23.66],
            ['sat_line' => 'MCBT54', 'sat_description' => 'INST_INTERRUP_TERMOMAG_ TIPO CAJA MOLDEADA MAYOR A 500 HASTA 800A', 'unit' => 'UNIDAD', 'unit_price' => 23.66],
            ['sat_line' => 'MCBT55', 'sat_description' => 'INST_INTERRUP_TERMOMAG_ TIPO CAJA MOLDEADA MAYOR A 800 HASTA 1000A', 'unit' => 'UNIDAD', 'unit_price' => 23.66],
            ['sat_line' => 'MCBT56', 'sat_description' => 'INST_INTERRUP_TERMOMAG_, PULSADOR, SELECTOR O CONMUTADOR DE 63 A 120 AMP. (TRIPOLAR)', 'unit' => 'UNIDAD', 'unit_price' => 64.27],
            ['sat_line' => 'MCBT57', 'sat_description' => 'INST_INTERRUP_TERMOMAG_, PULSADOR, SELECTOR O CONMUTADOR HASTA 63 AMP. (TRIPOLAR)', 'unit' => 'UNIDAD', 'unit_price' => 64.27],
            ['sat_line' => 'MCBT58', 'sat_description' => 'INSTAL_PORTA PLANOS PARA TABLEROS ELÉCTRICOS (INCLUYE DESINSTALACIÓN EN CASO SEA NECESARIO)', 'unit' => 'UNIDAD', 'unit_price' => 20.63],
            ['sat_line' => 'MCBT59', 'sat_description' => 'INSTAL_RELÉ TÉRMICO (HASTA 63 AMP.)', 'unit' => 'UNIDAD', 'unit_price' => 20.00],
            ['sat_line' => 'MCBT60', 'sat_description' => 'INSTAL_RELES Y SENSORES TOROIDALES DE FUGAS A TIERRA EN ACOMETIDAS Y SUBACOMETIDAS', 'unit' => 'UNIDAD', 'unit_price' => 62.32],
            ['sat_line' => 'MCBT61', 'sat_description' => 'INSTAL_STICKER (RÓTULO) EN TABLERO ELÉCTRICO, DE 11 A 20 RÓTULOS', 'unit' => 'UNIDAD', 'unit_price' => 4.26],
            ['sat_line' => 'MCBT62', 'sat_description' => 'INSTAL_STICKER (RÓTULO) EN TABLERO ELÉCTRICO, DE 21 A MÁS RÓTULOS', 'unit' => 'UNIDAD', 'unit_price' => 4.26],
            ['sat_line' => 'MCBT63', 'sat_description' => 'INSTAL_STICKER (RÓTULO) EN TABLERO ELÉCTRICO, DE 3 A 10 RÓTULOS', 'unit' => 'UNIDAD', 'unit_price' => 4.26],
            ['sat_line' => 'MCBT64', 'sat_description' => 'INSTAL_SUPRESOR DE PICOS', 'unit' => 'UNIDAD', 'unit_price' => 19.00],
            ['sat_line' => 'MCBT65', 'sat_description' => 'INSTAL_TABLERO DISTRIBUCIÓN METÁLICO 14 POLOS', 'unit' => 'UNIDAD', 'unit_price' => 86.63],
            ['sat_line' => 'MCBT66', 'sat_description' => 'INSTAL_TAPA CIEGA PARA INTERRUPTORES, TOMACORRIENTES, OTROS.', 'unit' => 'UNIDAD', 'unit_price' => 5.20],
            ['sat_line' => 'MCBT67', 'sat_description' => 'INSTAL_TAPA DE RESERVA EN TABLERO ELÉCTRICO (PARA CUBRIR ESPACIOS DONDE SE INSTALAN LOS INTERRUPTORES)', 'unit' => 'UNIDAD', 'unit_price' => 5.20],
            ['sat_line' => 'MCBT68', 'sat_description' => 'INSTAL_TAPÓN EN TUBERÍA Y/O NIPLERÍA.', 'unit' => 'UNIDAD', 'unit_price' => 16.00],
            ['sat_line' => 'MCBT69', 'sat_description' => 'INSTAL_TERMINALES DESDE 35 MM2 HASTA 120 MM2', 'unit' => 'UNIDAD', 'unit_price' => 13.40],
            ['sat_line' => 'MCBT70', 'sat_description' => 'INSTAL_TERMINALES PARA CABLES DESDE 1.5 MM2 HASTA 6 MM2 DE Ø.', 'unit' => 'UNIDAD', 'unit_price' => 2.50],
            ['sat_line' => 'MCBT71', 'sat_description' => 'INSTAL_TERMINALES PARA CABLES DESDE 10 MM2 HASTA 25 MM2 DE Ø.', 'unit' => 'UNIDAD', 'unit_price' => 10.13],
            ['sat_line' => 'MCBT72', 'sat_description' => 'INSTAL_TRANSFORMADOR DE AISLAMIENTO O TENSIÓN 3 A 6 KVA 3? O 3?+N', 'unit' => 'UNIDAD', 'unit_price' => 45.92],
            ['sat_line' => 'MCBT73', 'sat_description' => 'INSTAL_TRANSFORMADOR DE AISLAMIENTO O TENSIÓN 7 A 10 KVA 3? O 3?+N', 'unit' => 'UNIDAD', 'unit_price' => 400.39],
            ['sat_line' => 'MCBT74', 'sat_description' => 'INSTAL_TRANSFORMADOR DE AISLAMIENTO TENSIÓN 11 A 20 KVA 3? O 3?+N', 'unit' => 'UNIDAD', 'unit_price' => 436.55],
            ['sat_line' => 'MCBT75', 'sat_description' => 'INSTALACIÓN TABLERO DE PVC DE 10 A 12 POLOS', 'unit' => 'UNIDAD', 'unit_price' => 90.00],
            ['sat_line' => 'MCBT76', 'sat_description' => 'INSTALACIÓN Y PROGRAMACIÓN DE INTERRUPTOR HORARIO (TIMER)', 'unit' => 'UNIDAD', 'unit_price' => 51.33],
            ['sat_line' => 'MCBT77', 'sat_description' => 'MEGADO DE CONDUCTOR (ESTA LÍNEA APLICA SÓLO PARA CASOS QUE ESTÉN FUERA DEL MANTENIMIENTO PREVENTIVO Y LAS OBSERVACIONES QUE DERIVEN DE ELLA)', 'unit' => 'UNIDAD', 'unit_price' => 14.68],
            ['sat_line' => 'MCBT78', 'sat_description' => 'MONTAJE DE BARRA DE COBRE EN TABLERO ELÉCTRICO', 'unit' => 'UNIDAD', 'unit_price' => 130.52],
            ['sat_line' => 'MCBT79', 'sat_description' => 'MONTAJE DE CABLES DE SECCIÓN HASTA 16 MM2. INCLUYE EL DESMONTAJE DEL CABLEADO EN MAL ESTADO. NOTA: EL PRECIO DE ESTA LÍNEA ES POR ML DEL TENDIDO E INCLUYE LAS 2, 3 O TODAS LAS FASES DEL CIRCUITO.', 'unit' => 'ML', 'unit_price' => 14.00],
            ['sat_line' => 'MCBT80', 'sat_description' => 'MONTAJ_CABLES DESDE 25 MM2 DE SECCIÓN HASTA 50 MM2. INCLUYE EL DESMONTAJE DEL CABLEADO EN MAL ESTADO.', 'unit' => 'ML', 'unit_price' => 18.00],
            ['sat_line' => 'MCBT81', 'sat_description' => 'MONTAJ_CABLES DESDE 70 MM2 A 120MM2 DE SECCIÓN. INCLUYE EL DESMONTAJE DEL CABLEADO EN MAL ESTADO.', 'unit' => 'ML', 'unit_price' => 31.00],
            ['sat_line' => 'MCBT82', 'sat_description' => 'MONTAJ_CABLES MAYORES A 120MM2 DE SECCIÓN . INCLUYE EL DESMONTAJE DEL CABLEADO EN MAL ESTADO.', 'unit' => 'ML', 'unit_price' => 43.32],
            ['sat_line' => 'MCBT83', 'sat_description' => 'MONTAJ_CAJA Y BOTÓN DE PARADA DE EMERGENCIA (INCLUYE CONEXIONES Y HABILITACIÓN DEL INTERRUPTOR)', 'unit' => 'UNIDAD', 'unit_price' => 17.33],
            ['sat_line' => 'MCBT84', 'sat_description' => 'MONTAJ_CAJAS DE DERIVACIÓN DE PASE DE 10X10PULG EN ADELANTE', 'unit' => 'UNIDAD', 'unit_price' => 17.33],
            ['sat_line' => 'MCBT85', 'sat_description' => 'MONTAJ_CAJAS DE DERIVACIÓN DE PASE DE 6X6PUG HASTA 10X10PULG', 'unit' => 'UNIDAD', 'unit_price' => 11.00],
            ['sat_line' => 'MCBT86', 'sat_description' => 'MONTAJ_CAJAS DE DERIVACIÓN DE PASE HASTA 4X4PULG', 'unit' => 'UNIDAD', 'unit_price' => 10.40],
            ['sat_line' => 'MCBT87', 'sat_description' => 'MONTAJ_CANALETA DE PVC (HASTA 160 MM), COLOCADA EN CUADROS O EN SUPERFICIE (INCLUYE EL MONTAJ_LOS ACCESORIOS NECESARIOS COMO ÁNGULOS Y LOS MATERIALES CONSUMIBLES).', 'unit' => 'ML', 'unit_price' => 16.86],
            ['sat_line' => 'MCBT88', 'sat_description' => 'MONTAJ_CONDENSADOR PARA TABLERO DE BANCO DE CONDESADORES', 'unit' => 'UNIDAD', 'unit_price' => 60.21],
            ['sat_line' => 'MCBT89', 'sat_description' => 'MONTAJ_MANDIL DE PROTECCIÓN EN TABLERO ELÉCTRICO. (LA LÍNEA SOLO DEBERÁ USARSE CUANDO EL MANDIL HAYA SIDO FABRICADO POR EL PROVEEDOR).', 'unit' => 'UNIDAD', 'unit_price' => 27.66],
            ['sat_line' => 'MCBT90', 'sat_description' => 'MONTAJ_MAYOLICA O PORCELANATO', 'unit' => 'M2', 'unit_price' => 22.25],
            ['sat_line' => 'MCBT91', 'sat_description' => 'MONTAJ_OMEGAS (ACCESORIO QUE USAMOS PARA NIVELAR LOS INTERRUPTORES TERMOMAGNETICOS Y DIFERENCIALES AL MANDIL DEL TABLERO)', 'unit' => 'UNIDAD', 'unit_price' => 15.00],
            ['sat_line' => 'MCBT92', 'sat_description' => 'MONTAJ_RACK O BANDEJA (PARA SOSTENER ALGÚN EQUIPO O ELEMENTO. EJM: ESTABILIZADOR, TRANSFORMADOR,UPS).', 'unit' => 'UNIDAD', 'unit_price' => 21.25],
            ['sat_line' => 'MCBT93', 'sat_description' => 'MONTAJE DE RIEL DIN', 'unit' => 'UNIDAD', 'unit_price' => 16.25],
            ['sat_line' => 'MCBT94', 'sat_description' => 'MONTAJ_SENSOR DE PRESENCIA', 'unit' => 'UNIDAD', 'unit_price' => 25.99],
            ['sat_line' => 'MCBT95', 'sat_description' => 'MONTAJ_TAPA DE METAL PARA CAJA DE REGISTRO (POZO A TIERRA). INCLUYE TODOS AQUELLOS TRABAJOS NECESARIOS PARA REALIZAR LA TAREA Y LOS MATERIALES CONSUMIBLES.', 'unit' => 'UNIDAD', 'unit_price' => 26.39],
            ['sat_line' => 'MCBT96', 'sat_description' => 'MONTAJ_TRANSFORMADOR DE AISLAMIENTO  10KVA', 'unit' => 'UNIDAD', 'unit_price' => 324.18],
            ['sat_line' => 'MCBT97', 'sat_description' => 'MONTAJ_TRANSFORMADOR DE AISLAMIENTO  20KVA', 'unit' => 'UNIDAD', 'unit_price' => 371.00],
            ['sat_line' => 'MCBT98', 'sat_description' => 'MONTAJ_TRANSFORMADOR DE AISLAMIENTO  30KVA', 'unit' => 'UNIDAD', 'unit_price' => 354.21],
            ['sat_line' => 'MCBT99', 'sat_description' => 'MONTAJ_TRANSFORMADOR DE AISLAMIENTO  40KVA', 'unit' => 'UNIDAD', 'unit_price' => 362.48],
            ['sat_line' => 'MCBT100', 'sat_description' => 'MONTAJ_TUBERÍA CONDUIT (DESDE 1 1/2" HASTA 4"), INCLUYE TODO LOS ACCESORIOS EN SU RECORRIDO COMO ABRAZADERAS, RIEL UNISTRUD, CONECTORES, CURVAS, UNIONES, ETC', 'unit' => 'ML', 'unit_price' => 20.63],
            ['sat_line' => 'MCBT101', 'sat_description' => 'MONTAJ_TUBERÍA CONDUIT (DESDE 1 1/4" HASTA 2"), INCLUYE TODO LOS ACCESORIOS EN SU RECORRIDO COMO ABRAZADERAS, RIEL UNISTRUD, CONECTORES, CURVAS, UNIONES, ETC', 'unit' => 'ML', 'unit_price' => 14.44],
            ['sat_line' => 'MCBT102', 'sat_description' => 'MONTAJ_TUBERÍA CONDUIT (HASTA 1"), INCLUYE TODO LOS ACCESORIOS EN SU RECORRIDO COMO ABRAZADERAS, RIEL UNISTRUD, CONECTORES, CURVAS, UNIONES, ETC', 'unit' => 'ML', 'unit_price' => 8.67],
            ['sat_line' => 'MCBT103', 'sat_description' => 'MONTAJ_TUBERÍA DE PVC (DESDE 1 1/4" EN ADELANTE), INCLUYE TODO LOS ACCESORIOS EN SU RECORRIDO COMO ABRAZADERAS, RIEL UNISTRUD, CONECTORES, CURVAS, UNIONES, ETC', 'unit' => 'ML', 'unit_price' => 9.29],
            ['sat_line' => 'MCBT104', 'sat_description' => 'MONTAJ_TUBERÍA DE PVC (HASTA 1"), INCLUYE TODO LOS ACCESORIOS EN SU RECORRIDO COMO ABRAZADERAS, RIEL UNISTRUD, CONECTORES, CURVAS, UNIONES, ETC', 'unit' => 'ML', 'unit_price' => 7.50],
            ['sat_line' => 'MCBT105', 'sat_description' => 'MONTAJ_TUBERÍA LIQUID TIGHT (CONDUIT FLEXIBLE) DE 1 1/2 HASTA 3" INCLUYE TODO LOS ACCESORIOS EN SU RECORRIDO COMO ABRAZADERAS, RIEL UNISTRUD, CONECTORES, CURVAS, UNIONES, ETC', 'unit' => 'ML', 'unit_price' => 44.00],
            ['sat_line' => 'MCBT106', 'sat_description' => 'MONTAJ_TUBERÍA LIQUID TIGHT (CONDUIT FLEXIBLE) HASTA 1"  INCLUYE TODO LOS ACCESORIOS EN SU RECORRIDO COMO ABRAZADERAS, RIEL UNISTRUD, CONECTORES, CURVAS, UNIONES, ETC', 'unit' => 'ML', 'unit_price' => 25.00],
            ['sat_line' => 'MCBT107', 'sat_description' => 'MONTAJE E INSTALACIÓN ARRANCADOR SUAVE EN EQUIPO DE AA Y/O COMPRESOR DE AIRE.', 'unit' => 'UNIDAD', 'unit_price' => 324.18],
            ['sat_line' => 'MCBT108', 'sat_description' => 'MONTAJE E INSTALACIÓN DE MEDIDOR DE ENERGÍA. INCLUYE LA CONEXIÓN Y TRABAJOS PREVIOS NECESARIOS.', 'unit' => 'UNIDAD', 'unit_price' => 164.00],
            ['sat_line' => 'MCBT109', 'sat_description' => 'MONTAJE E INSTALACIÓN DE TRANSFORMADORES DE CORRIENTE PARA MEDIDORES DE ENERGIA (PACK DE TRES FASES)', 'unit' => 'UNIDAD', 'unit_price' => 159.35],
            ['sat_line' => 'MCBT110', 'sat_description' => 'MONTAJE Y CONEXIÓN DE PILOTO DE SEÑALIZACIÓN', 'unit' => 'UNIDAD', 'unit_price' => 14.31],
            ['sat_line' => 'MCBT111', 'sat_description' => 'MONTAJE Y CONFIGURACIÓN DE MÓDULO DE REGULACIÓN DE ETAPAS PARA TABLERO DE BANCO DE CONDESADORES', 'unit' => 'UNIDAD', 'unit_price' => 164.00],
            ['sat_line' => 'MCBT112', 'sat_description' => 'ORDENAMIENDO DE CABLES EN OFICINAS, ÁREA DE CAJA . (INCLUYE LOS MATERIALES CONSUMIBLES Y AQUELLOS NECESARIOS PARA LA ACTIVIDAD MENCIONADA, CINTILLOS, CINTA ESPIRAL, ETC).', 'unit' => 'UNIDAD', 'unit_price' => 230.58],
            ['sat_line' => 'MCBT113', 'sat_description' => 'PICADO, RESANE Y PINTADO DE PARED, PISO O TECHO PARA EL MONTAJE DE CAJAS O TABLEROS ELECTRICOS (INCLUYE LOS MATERIALES CONSUMIBLES).', 'unit' => 'M2', 'unit_price' => 136.99],
            ['sat_line' => 'MCBT114', 'sat_description' => 'PICADO, RESANE Y PINTADO DE PARED, PISO O TECHO PARA EL MONTAJE DE TUBERÍA DE HASTA 2" DE DIÁMETRO (INCLUYE LOS MATERIALES CONSUMIBLES).', 'unit' => 'ML', 'unit_price' => 60.00],
            ['sat_line' => 'MCBT115', 'sat_description' => 'PINTADO DE TABLERO (POR PRESENCIA DE OXIDO)', 'unit' => 'UNIDAD', 'unit_price' => 36.00],
            ['sat_line' => 'MCBT116', 'sat_description' => 'PORTA PLANOS PARA TABLEROS ELÉCTRICOS.', 'unit' => 'UNIDAD', 'unit_price' => 30.00],
            ['sat_line' => 'MCBT117', 'sat_description' => 'PROGRAMACIÓN DE HORARIO EN PLC', 'unit' => 'UNIDAD', 'unit_price' => 98.00],
            ['sat_line' => 'MCBT118', 'sat_description' => 'PROGRAMACIÓN DE HORARIO EN PLC O TIMER ANÁLOGICO PARA EL ENCENDIDO DE LUCES EN MARQUESINA Y/O OTROS.', 'unit' => 'UNIDAD', 'unit_price' => 135.94],
            ['sat_line' => 'MCBT119', 'sat_description' => 'PROGRAMACIÓN DE INTERRUPTOR HORARIO', 'unit' => 'UNIDAD', 'unit_price' => 90.96],
            ['sat_line' => 'MCBT120', 'sat_description' => 'RESANE DE LOZA DE CONCRETO  HASTA 0.2M DE PROFUNDIDAD(A TODO COSTO, INCLUYE EL CONCRETO NECESARIO RESISTENCIA 210KG/CM2).', 'unit' => 'M2', 'unit_price' => 120.00],
            ['sat_line' => 'MCBT121', 'sat_description' => 'RESANE DE PISTA ASFÁLTICA  CON CONCRETO Y OCRE NEGRO HASTA 0.2M (A TODO COSTO, INCLUYE EL ASFALTO).', 'unit' => 'M2', 'unit_price' => 237.36],
            ['sat_line' => 'MCBT122', 'sat_description' => 'RETIRO DE TABLERO ELÉCTRICO EXISTENTE, INCLUYE: - RETIRO DE DISPOSITIVOS (AQUELLOS QUE SE PODRÁN REUTILIZAR, SERÁN ENTREGADOS AL ÁREA DE MTTO EN UNA CAJA INVENTARIADA). - DESCONEXIÓN DE CIRCUITOS. - RETIRO DE TABLERO (INCLUYE RETIRO DE CAJA, TAPA, PUERTA Y AQUELLOS TRABAJOS NECESARIOS PARA EJECUTAR LA TAREA).', 'unit' => 'UNIDAD', 'unit_price' => 237.36],
            ['sat_line' => 'MCBT123', 'sat_description' => 'RETIRO E INSTALACIÓN DE EQUIPO DE LUZ DE EMERGENCIA', 'unit' => 'UNIDAD', 'unit_price' => 44.00],
            ['sat_line' => 'MCBT124', 'sat_description' => 'RETIRO Y ELIMINACIÓN DE DESMONTE.', 'unit' => 'M3', 'unit_price' => 149.35],
            ['sat_line' => 'MCBT125', 'sat_description' => 'ROTULADO DE CIRCUITO ELÉCTRICO (INCLUYE SUMINSTRO DE LOS ROTULOS EN LOS CABLES POR CIRCUITO)', 'unit' => 'UNIDAD', 'unit_price' => 6.50],
            ['sat_line' => 'MCBT126', 'sat_description' => 'ROTURA DE LOZA DE CONCRETO HASTA 0.2 M DE PROFUNDIDAD (A TODO COSTO).', 'unit' => 'M2', 'unit_price' => 113.69],
            ['sat_line' => 'MCBT127', 'sat_description' => 'ROTURA DE PISTA ASFÁLTICA HASTA 0.2 M DE PROFUNDIDAD (A TODO COSTO).', 'unit' => 'M2', 'unit_price' => 151.60],
            ['sat_line' => 'MCBT128', 'sat_description' => 'SUSTITUCIÓN O MONTAJE DE PRENSAESTOPAS (DESDE 1" HASTA 1 1/4"), EN COFRET, CUADRO, CAJA DE DERIVACIÓN, ETC; INCLUYENDO LA CONEXIÓN DEL CABLE.', 'unit' => 'UNIDAD', 'unit_price' => 18.00],
            ['sat_line' => 'MCBT129', 'sat_description' => 'SUSTITUCIÓN O MONTAJE DE PRENSAESTOPAS (HASTA 3/4"), EN COFRET, CUADRO, CAJA DE DERIVACIÓN, ETC., INCLUYENDO LA CONEXIÓN DEL CABLE.', 'unit' => 'UNIDAD', 'unit_price' => 15.00],
            ['sat_line' => 'MCBT130', 'sat_description' => 'TRAT_ACEITE_TRANSFORM_SISTEMA_ TERMOVACIO HASTA 250 KVA', 'unit' => 'UNIDAD', 'unit_price' => 458.00],
            ['sat_line' => 'MCBT131', 'sat_description' => 'TRAT_ACEITE_TRANSFORM_SISTEMA_ TERMOVACIO HASTA 500 KVA', 'unit' => 'UNIDAD', 'unit_price' => 915.42],
            ['sat_line' => 'MCBT132', 'sat_description' => 'TRAT_ACEITE_TRANSFORM_SISTEMA_ TERMOVACIO HASTA 800 KVA', 'unit' => 'UNIDAD', 'unit_price' => 1376.00],
            ['sat_line' => 'MCBT133', 'sat_description' => 'PLOTEO PLANOS EN A0', 'unit' => 'UNIDAD', 'unit_price' => 14.00],
            ['sat_line' => 'MCBT134', 'sat_description' => 'ABRAZADERA GALVANIZADA (ESTÁNDAR) - UNISTRUD - 1 1/2"', 'unit' => 'UNIDAD', 'unit_price' => 2.00],
            ['sat_line' => 'MCBT135', 'sat_description' => 'ABRAZADERA GALVANIZADA (ESTÁNDAR) - UNISTRUD - 1"', 'unit' => 'UNIDAD', 'unit_price' => 2.00],
            ['sat_line' => 'MCBT136', 'sat_description' => 'ABRAZADERA GALVANIZADA (ESTÁNDAR) - UNISTRUD - 2"', 'unit' => 'UNIDAD', 'unit_price' => 2.00],
            ['sat_line' => 'MCBT137', 'sat_description' => 'ABRAZADERA GALVANIZADA (ESTÁNDAR) - UNISTRUD - 3"', 'unit' => 'UNIDAD', 'unit_price' => 4.00],
            ['sat_line' => 'MCBT138', 'sat_description' => 'ABRAZADERA GALVANIZADA (ESTÁNDAR) - UNISTRUD - 3/4"', 'unit' => 'UNIDAD', 'unit_price' => 2.00],
            ['sat_line' => 'MCBT139', 'sat_description' => 'ABRAZADERA GALVANIZADA (PESADA) - 1"', 'unit' => 'UNIDAD', 'unit_price' => 2.00],
            ['sat_line' => 'MCBT140', 'sat_description' => 'ABRAZADERA GALVANIZADA (PESADA) - 1/2"', 'unit' => 'UNIDAD', 'unit_price' => 1.00],
            ['sat_line' => 'MCBT141', 'sat_description' => 'ABRAZADERA GALVANIZADA (PESADA) - 2"', 'unit' => 'UNIDAD', 'unit_price' => 3.00],
            ['sat_line' => 'MCBT142', 'sat_description' => 'ABRAZADERA GALVANIZADA (PESADA) - 3"', 'unit' => 'UNIDAD', 'unit_price' => 4.00],
            ['sat_line' => 'MCBT143', 'sat_description' => 'ABRAZADERA GALVANIZADA (PESADA) - 3/4"', 'unit' => 'UNIDAD', 'unit_price' => 1.00],
            ['sat_line' => 'MCBT144', 'sat_description' => 'ABRAZADERA GALVANIZADA (PESADA) - 4"', 'unit' => 'UNIDAD', 'unit_price' => 4.00],
            ['sat_line' => 'MCBT145', 'sat_description' => 'ANALIZADOR DE ENERGÍA,PM5330,  31 ARMÓNICO, MEMORIA INTERNA 256KB, IP65 + ACCESORIO, SERIAL', 'unit' => 'UNIDAD', 'unit_price' => 2098.00],
            ['sat_line' => 'MCBT146', 'sat_description' => 'ANALIZADOR DE REDES PARA PANEL 96X96MM PARA MONTAJE EN TABLERO CIRCUTOR CVM C10', 'unit' => 'UNIDAD', 'unit_price' => 1033.00],
            ['sat_line' => 'MCBT147', 'sat_description' => 'ANGULO EXTERIOR DE 110 X 50 MM 10096RBR EFAPEL', 'unit' => 'UNIDAD', 'unit_price' => 10.25],
            ['sat_line' => 'MCBT148', 'sat_description' => 'ANGULO EXTERIOR DE 20 X 12.5 MM EFAPHEL', 'unit' => 'UNIDAD', 'unit_price' => 4.00],
            ['sat_line' => 'MCBT149', 'sat_description' => 'ANGULO EXTERIOR DE 50 X 20 MM LEGRAND DLP-S 638162', 'unit' => 'UNIDAD', 'unit_price' => 6.82],
            ['sat_line' => 'MCBT150', 'sat_description' => 'ANGULO INTERNO DE 110 X 50 MM 10092RBR EFAPEL', 'unit' => 'UNIDAD', 'unit_price' => 10.25],
        ];

        foreach ($pricelists as $item) {
            $unit = Unit::firstOrCreate(
                ['symbol' => $item['unit']],
                ['name' => $item['unit'], 'category' => 'SERVICIO']
            );

            Pricelist::create([
                'sat_line' => $item['sat_line'],
                'sat_description' => $item['sat_description'],
                'unit_id' => $unit->id,
                'unit_price' => $item['unit_price'],
                'price_type_id' => $priceType->id,
            ]);
        }
    }
}
