<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SubClient;

class SubClientSeeder extends Seeder
{

    public function run(): void
    {
        $data = [

            [
                'id' => 1,
                'client_id' => 1,
                'name' => 'CPP - CEMENTOS PACASMAYO - PIURA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'client_id' => 1,
                'name' => 'CPL - CEMENTOS PACASMAYO - LA LIBERTAD',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'client_id' => 16,
                'name' => 'CEP-CLEAN ENERGY DEL PERU',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'client_id' => 14,
                'name' => 'PMK - PROCESO MUCHIK',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'client_id' => 12,
                'name' => 'PAG-PLASTICOS AGRICOLAS Y GEOMEMBRANAS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'client_id' => 11,
                'name' => 'GRL-GOBIERNO REGIONAL LAMBAYEQUE',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'client_id' => 8,
                'name' => 'CMM-MISKI MAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'client_id' => 7,
                'name' => 'CARTAVIO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'client_id' => 4,
                'name' => 'AO - AGROLMOS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'client_id' => 3,
                'name' => 'ASJ-AGROINDUSTRIAS SAN JACINTO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'client_id' => 5,
                'name' => 'ANDALUCITA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'client_id' => 6,
                'name' => 'CG - CASA GRANDE',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'client_id' => 20,
                'name' => 'ASL-AGROINDUSTRIAL LAREDO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'client_id' => 2,
                'name' => 'AA - AGROAURORA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'client_id' => 9,
                'name' => 'DSM',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 16,
                'client_id' => 10,
                'name' => 'GAT',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'client_id' => 17,
                'name' => 'HAY-PESQUERA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'client_id' => 13,
                'name' => 'DNP-DINO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'client_id' => 19,
                'name' => 'CORPORACION PLASTIC GL S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'client_id' => 18,
                'name' => 'ECOSAC AGRICOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'client_id' => 15,
                'name' => 'IPR-INVERSIONES PRISCO S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'client_id' => 21,
                'name' => 'TRU-TRUPAL S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'client_id' => 22,
                'name' => 'ER-EL ROCIO S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'client_id' => 23,
                'name' => 'AR - SOCIEDAD AGRICOLA RAPEL SAC',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'client_id' => 24,
                'name' => 'PPP - PLANTA DE POSTES PIURA S.R.L',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'client_id' => 25,
                'name' => 'CONGRESO DE LA REPUBLICA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'client_id' => 26,
                'name' => 'CAA- CORPORACION ACEROS AREQUIPA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'client_id' => 27,
                'name' => 'MAL-MONTERREY AZUCARERA LOJANA C.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'client_id' => 28,
                'name' => 'CAYNARACHI S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'client_id' => 29,
                'name' => 'CSJ - CONSORCIO CARSOL - JRM S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'client_id' => 30,
                'name' => 'ADC-AGRICOLA DEL CHIRA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 32,
                'client_id' => 31,
                'name' => 'PDP-PETROLEOS DEL PERU PETROPERU SA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'client_id' => 33,
                'name' => 'UNA- UNNA ENERGIA S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'client_id' => 34,
                'name' => 'UNE -UNIV.NAC.DE EDUC. ENRIQUE GUZMAN Y VALLE',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'client_id' => 35,
                'name' => 'OCS - OCEANO SEAFOOD S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'client_id' => 36,
                'name' => 'MIC - MILICIC PERU S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'client_id' => 37,
                'name' => 'CHR - CHINA RAILWAY N° 10 ENGINEERING GROUP CO., LTD SUCURSAL DEL PERU',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'client_id' => 38,
                'name' => 'YOF-YOFC PERU S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'client_id' => 39,
                'name' => 'SHE-SUNSHINE EXPORT S.A.C',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'client_id' => 40,
                'name' => 'PAL - PESQUERA ALTAIR S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'client_id' => 40,
                'name' => 'PAL-PESQUERA ALTAIR S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'client_id' => 41,
                'name' => 'UNP - UNIVERSIDAD NACIONAL DE PIURA ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'client_id' => 43,
                'name' => 'LDN-LADRINORTE S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'client_id' => 44,
                'name' => 'HJH - HOSPITAL JOSE HERNÁN SOTO CADENILLAS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'client_id' => 45,
                'name' => 'VTP - VITAPRO S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'client_id' => 46,
                'name' => 'AGC - AGROFUTURA COMPANY S.A.C. ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'client_id' => 47,
                'name' => 'IMT- INGEMMET',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 49,
                'client_id' => 48,
                'name' => 'DNP - DANPER AGRICOLA OLMOS S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'client_id' => 49,
                'name' => 'CPR',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'client_id' => 50,
                'name' => 'AVO-AVOAMERICA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'client_id' => 51,
                'name' => 'GAL',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'client_id' => 52,
                'name' => 'APC - AVOCADO PACKING COMPANY',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'client_id' => 53,
                'name' => 'MPW - MANPOWER PROFESSIONAL SERVICES S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'client_id' => 54,
                'name' => 'DPT - DANPER TRUJILLO S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'client_id' => 55,
                'name' => 'JPS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'client_id' => 56,
                'name' => 'SPS -  SUPERMERCADOS PERUANOS S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'client_id' => 57,
                'name' => 'CONSORCIO PIURA - CSP',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'client_id' => 58,
                'name' => 'PAITA INGREDIENTS S.A.C. - PIS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'client_id' => 59,
                'name' => 'TRANSPORTES Y SERVICIOS GENERALES LARA EIRL - TSG',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'client_id' => 60,
                'name' => 'EPS-ENTIDAD PRESTADORA DE SERVICIOS DE SANEAMIENTO GRAU',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'client_id' => 61,
                'name' => 'SFP-SUPERFOODS PERU S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'client_id' => 62,
                'name' => 'ALS - ALMACENES SUDAMERICANOS S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'client_id' => 63,
                'name' => 'VC - V&C S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'client_id' => 64,
                'name' => 'CEYESA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'client_id' => 65,
                'name' => 'GDP - GASES DEL PACÍFICO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'client_id' => 66,
                'name' => 'MTA - CONSORCIO MONTE AZUL S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'client_id' => 67,
                'name' => 'MBM - MINERA BOROO MISQUICHILCA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'client_id' => 68,
                'name' => 'IMC - INMOBILIARIA LAS CUMBRES S.A.C',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'client_id' => 69,
                'name' => 'ILC - INVERSIONES LA CRUZ S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'client_id' => 70,
                'name' => 'MVS - MV SERVICIOS S.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'client_id' => 71,
                'name' => 'KCP - KAESER COMPRESORES DE PERU S.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'client_id' => 72,
                'name' => 'FMG-FAMEGSA E.I.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'client_id' => 73,
                'name' => 'SBT - SMART BUSINESS TEC S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'client_id' => 74,
                'name' => 'GCI - GLOBAL CITRUS INTERNATIONAL SOCIEDAD ANONIMA CERRADA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'client_id' => 75,
                'name' => 'SGG - SERVICIOS GENERALES GADENN E.I.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'client_id' => 76,
                'name' => 'FHT - F & H TRANSPORTES Y SERVICIOS SAC',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'client_id' => 77,
                'name' => 'SEN - SENATI',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'client_id' => 60,
                'name' => 'EPS - ENTIDAD PRESTADORA DE SERVICIOS DE SANEAMIENTO GRAU',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'client_id' => 78,
                'name' => 'MRS - MARINASOL S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 82,
                'client_id' => 79,
                'name' => 'CPS - CITRICOS PERUANOS S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'client_id' => 80,
                'name' => 'AI - AGROMAR INDUSTRIAL S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'client_id' => 81,
                'name' => 'PUF-PUFFER PERU S.R.L',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'client_id' => 82,
                'name' => 'NFM-NATIONAL FACILITIES MANAGEMENT S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'client_id' => 83,
                'name' => 'LM - LARCO MAR S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'client_id' => 84,
                'name' => 'TAV-TECNICA AVICOLA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'client_id' => 85,
                'name' => 'PDM-PROVEEDORA DE PRODUCTOS MARINOS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'client_id' => 86,
                'name' => 'PSF-PERUVIAN SEA FOOD S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'client_id' => 87,
                'name' => 'PPS-PRECISION PERU S.A. ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'client_id' => 88,
                'name' => 'EMC-EMBOTELLADORA CARAL S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'client_id' => 89,
                'name' => 'MSX - MINERA SHOUXIN PERU S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'client_id' => 90,
                'name' => 'IT -INDUSTRIAS DEL TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'client_id' => 91,
                'name' => 'OA - OLEAGINOSAS AMAZONICAS S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'client_id' => 92,
                'name' => 'RFH- REFRIGERADOS FISHOLG & HIJOS ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'client_id' => 93,
                'name' => 'PAC-PRODUCTORA ANDINA DE CONGELADOS S.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 98,
                'client_id' => 95,
                'name' => 'EAP-EMPRESA AGROINDUSTRIAL POMALCA ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'client_id' => 96,
                'name' => 'LIF-LADRILLOS INKA FORTE S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'client_id' => 96,
                'name' => 'LF-LADRILLOS FORTES S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'client_id' => 94,
                'name' => 'OSP-OCHO SUR P S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'client_id' => 97,
                'name' => 'H20-H2OLMOS S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'client_id' => 98,
                'name' => 'ICP-INSUMOS CORPORATIVOS PERU E.I.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'client_id' => 99,
                'name' => 'CPI-CORPORACIÓN PESQUERA INCA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 105,
                'client_id' => 21,
                'name' => 'TRUPAL - SULLANA ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 106,
                'client_id' => 100,
                'name' => 'MNT - MONTANA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'client_id' => 101,
                'name' => 'SEV - SEVIDON S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 108,
                'client_id' => 101,
                'name' => 'SON - SEVIDON S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'client_id' => 102,
                'name' => 'ACS-AGROPECUARIA CHIMU S.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 110,
                'client_id' => 103,
                'name' => 'EPE - EL PEDREGAL S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 111,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 112,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 113,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 114,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 115,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 116,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 117,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 118,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 119,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 120,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 121,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 122,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 123,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 124,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 125,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 126,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 127,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 128,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 135,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 136,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 137,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 138,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 139,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 140,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 141,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 142,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 143,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 144,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 145,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 146,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 147,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 148,
                'client_id' => 99,
                'name' => 'COPEINCA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 149,
                'client_id' => 104,
                'name' => 'SCC - SAN CARLOS CONTRATISTAS GENERALES S.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 150,
                'client_id' => 105,
                'name' => 'PRA - PROCESOS AGROINDUSTRIALES S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 151,
                'client_id' => 106,
                'name' => 'UPE - UNACEM PERU S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 152,
                'client_id' => 107,
                'name' => 'CI -CALIZA CEMENTO INCA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 153,
                'client_id' => 106,
                'name' => 'UPE - UNACEM PERU S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 155,
                'client_id' => 108,
                'name' => 'DIRECCIÓN DE GESTIÓN DE RECURSOS EDUCATIVOS - DIGERE',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 156,
                'client_id' => 109,
                'name' => 'TRANSBAL EXPRESS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 157,
                'client_id' => 110,
                'name' => 'ELECTRONORTE SA.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 158,
                'client_id' => 111,
                'name' => 'DIGERE',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 159,
                'client_id' => 112,
                'name' => 'GRP - GOBIERNO REGIONAL DE PIURA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 160,
                'client_id' => 113,
                'name' => 'EUROANDINO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 161,
                'client_id' => 114,
                'name' => 'MP',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 162,
                'client_id' => 1,
                'name' => 'CPS-CEMENTOS PACASMAYO-SELVA ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 163,
                'client_id' => 115,
                'name' => 'ABAINCOR EIRL',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 164,
                'client_id' => 74,
                'name' => 'GCI',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 165,
                'client_id' => 116,
                'name' => 'EPM - EMPREMAR E.I.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 166,
                'client_id' => 117,
                'name' => 'PPA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 167,
                'client_id' => 118,
                'name' => ' FLP DEL PERU S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 168,
                'client_id' => 119,
                'name' => 'WENCO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 169,
                'client_id' => 120,
                'name' => 'FEIMI',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 170,
                'client_id' => 121,
                'name' => 'PFP',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 171,
                'client_id' => 122,
                'name' => 'OL-OLYMPIC PERU INC SUCURSAL DEL PERU',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 172,
                'client_id' => 123,
                'name' => 'TA - TAMSHI S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 173,
                'client_id' => 124,
                'name' => 'RA - RANSA S.A.C. ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 174,
                'client_id' => 125,
                'name' => 'CONSORCIO AYESA- HMV',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 175,
                'client_id' => 126,
                'name' => 'SE-SEED FOOD S.A.C. ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 176,
                'client_id' => 127,
                'name' => 'Art Express - PVS',
                'description' => 'AV. NICOLÁS DE PIÉROLA N° 476',
                'location' => 'CERCADO DE LIMA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 177,
                'client_id' => 127,
                'name' => 'Ate - PVH',
                'description' => 'AV. NICOLAS AYLLON SECTOR B. MZ B LTE.4 ZONA A - BAJA ESQ. CON AV. LA MAR',
                'location' => 'ATE VITARTE, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 178,
                'client_id' => 127,
                'name' => 'Centro Trujillo - PVE',
                'description' => 'AV. ESPAÑA 2420 LA LIBERTAD TRUJILLO',
                'location' => 'TRUJILLO, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 179,
                'client_id' => 127,
                'name' => 'Cine Rimac - PVS',
                'description' => '',
                'location' => 'URB. VILLACAMPA. AV. FELIPE ARANCIBIA NO 455. RIMAC. - RIMAC, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 180,
                'client_id' => 127,
                'name' => 'El Chacarero - PVH',
                'description' => '',
                'location' => 'URB. LOS PORTALES MZ Q LT 1 TRUJILLO - TRUJILLO, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 181,
                'client_id' => 127,
                'name' => 'Jiron de la Union - PVE',
                'description' => '',
                'location' => 'JIRON DE LA UNION ESQUINA CON JIRON HUANCAVELICA S/N - CERCADO DE LIMA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 182,
                'client_id' => 127,
                'name' => 'Santa Clara - PVH',
                'description' => '',
                'location' => 'FUNDO LA ESTRELLA 99B CRUCE CON AV ESTRELLA - ATE VITARTE, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 183,
                'client_id' => 127,
                'name' => 'Trujillo Valcarcel - PVS',
                'description' => '',
                'location' => 'AV. TEODORO VALCARCEL 266 N° 268 URB. PRIMAVERA - LA LIBERTAD TRUJILLO - TRUJILLO, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 184,
                'client_id' => 127,
                'name' => 'Acho - PVH',
                'description' => '',
                'location' => 'JR MARAÑON 601-683 REF CALLE FAUSTO CASTAÑEDA 116-150 RIMAC, JUNTO A LA PLAZA DE TOROS. - RIMAC, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 185,
                'client_id' => 127,
                'name' => 'Ayacucho - PVS',
                'description' => '',
                'location' => 'MZ. B2 LT 10 URB. LOS ROSALES SURCO. (CDRA 1 DE AV. AYACUCHO) - SANTIAGO DE SURCO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ...existing code...
            [
                'id' => 186,
                'client_id' => 127,
                'name' => 'Comas - PVH',
                'description' => '',
                'location' => 'AV. TUPAC AMARU 3860,ALT. KM. 14.5 - COMAS, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 187,
                'client_id' => 127,
                'name' => 'Corpac - PVS',
                'description' => '',
                'location' => 'CALLE REMINGTON 151-159 - CALLE REMINGTON 151-159SAN BORJA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 188,
                'client_id' => 127,
                'name' => 'El Agustino - PVH',
                'description' => '',
                'location' => 'AV. CARLOS MARIÁTEGUI S/N ESQ. AV. LAS MAGNOLIAS SUB LOTE SECC.1 - EL AGUSTINO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 189,
                'client_id' => 127,
                'name' => 'Grifo Mexico - PVH',
                'description' => '',
                'location' => 'URB. SAN PABLO S/N . MZA 301 . FRENTE AV. MEXICO. LA VICTORIA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 190,
                'client_id' => 127,
                'name' => 'Izaguirre - PVH',
                'description' => '',
                'location' => 'AV. CARLOS IZAGUIRRE 284 - INDEPENDENCIA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 191,
                'client_id' => 127,
                'name' => 'La Victoria PVS',
                'description' => '',
                'location' => 'CALLE BOLIVAR 300-334 - LA VICTORIA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 192,
                'client_id' => 127,
                'name' => 'Pro - PVH',
                'description' => '',
                'location' => 'AV ALFREDO MENDIOLA MZ KM 21 LOTE 7008 - SAN MARTIN DE PORRAS, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 193,
                'client_id' => 127,
                'name' => 'Proceres - PVS',
                'description' => '',
                'location' => 'URBA. MARISCAL CÁCERES. AV. PRÓCERES DE LA INDEPENDENCIA S/N . LOTE 1. PROG. CIUDAD MRCAL CÁCERES SEC. II. SAN JUAN DE LURIGANCHO. SAN JUAN DE LURIGANCHO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 194,
                'client_id' => 127,
                'name' => 'Puente Piedra - PVH',
                'description' => '',
                'location' => 'AV. SAN LORENZO MZ. A, LT. 01 URB. LAS VEGAS PUENTE PIEDRA (ALTURA DEL OVALO PUENTE PIEDRA PAN. NORTE). PUENTE PIEDRA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 195,
                'client_id' => 127,
                'name' => 'Santa Cruz - PVE',
                'description' => '',
                'location' => 'AV. BELÉN 300 LOTE S/N BLOCK V - SAN ISIDRO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 196,
                'client_id' => 127,
                'name' => 'SJ Lurigancho - PVH',
                'description' => '',
                'location' => 'URB. QUINTA SAN FERNANDO S/N UNIDAD 44 C - SJL - SAN JUAN DE LURIGANCHO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 197,
                'client_id' => 127,
                'name' => 'Trujillo - PVH',
                'description' => '',
                'location' => 'FUNDO LAS CASUARINAS SUB LOTE PREDIO A LOTE 5 - TRUJILLO, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 198,
                'client_id' => 127,
                'name' => 'Trujillo Mansiche - PVS',
                'description' => '',
                'location' => 'AV ESPAÑA 780 (CALLE ZEPITA 583, CALLE GAMARRA 158) LA LIBERTAD TRUJILLO - TRUJILLO, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 199,
                'client_id' => 127,
                'name' => 'Alfonso Ugarte - PVH',
                'description' => '',
                'location' => 'AV. URUGUAY 568-596 ESQ. AV ALFONSO UGARTE 1103 AL 1179 CERCADO DE LIMA - CERCADO DE LIMA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 200,
                'client_id' => 127,
                'name' => 'Cajamarca - PVH',
                'description' => '',
                'location' => 'AV. EVITAMIENTO NORTE LOTE 1. CAJAMARCA, CAJAMARCA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 201,
                'client_id' => 127,
                'name' => 'Centro Civico - PVH',
                'description' => 'AV.INCA GARCILAZO DE LA VEGA NRO. 1383',
                'location' => 'CERCADO DE LIMA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 202,
                'client_id' => 127,
                'name' => 'Ceres - PVH',
                'description' => 'CARRETERA CENTRAL KM 6 . MZ M LOTE 2A',
                'location' => 'ATE VITARTE, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 203,
                'client_id' => 127,
                'name' => 'Chaclacayo - PVS',
                'description' => 'URB. CHACLACAYO. AV. NICOLAS AYLLON 582-598.',
                'location' => 'CHACLACAYO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 204,
                'client_id' => 127,
                'name' => 'Chiclayo - PVH',
                'description' => 'AV. MIGUEL DE CERVANTES 300 INT. LT. 6 C.C. REAL PLAZA',
                'location' => 'CHICLAYO, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 205,
                'client_id' => 127,
                'name' => 'Chiclayo Aventura - PVH',
                'description' => 'AV. PANAMERICANA 639',
                'location' => 'CHICLAYO, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 206,
                'client_id' => 127,
                'name' => 'Chosica - PVH',
                'description' => 'AV. LIMA SUR 930-970 CHOSICA',
                'location' => 'CHOSICA - LIMA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 207,
                'client_id' => 127,
                'name' => 'Universitaria - PVH',
                'description' => 'AV. UNIVERSITARIA NORTE 1632 URB. COMERCIAL DANIEL ALCIDES CARRION N° 1636 MZ A LT. 2',
                'location' => 'LOS OLIVOS, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 208,
                'client_id' => 127,
                'name' => 'Barranca - PVH',
                'description' => 'JR. ZAVALA S/N. CDRA 1   . LIMA-BARRANCA',
                'location' => 'BARRANCA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 209,
                'client_id' => 127,
                'name' => 'Chimbote - PVH',
                'description' => 'JR. FRANCISCO BOLOGNESI S/N (ESQ. JR. TUMBES) ANCASH SANTA - CHIMBOTE',
                'location' => 'CHIMBOTE, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 210,
                'client_id' => 127,
                'name' => 'El Tambo Huancayo - PVS',
                'description' => 'CALLE REAL MZ L LT. 13 URB. SAN ANTONIO DE PADUA  - JUNIN HUANCAYO - EL TAMBO',
                'location' => 'HUANCAYO, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 211,
                'client_id' => 127,
                'name' => 'Huacho - PVH',
                'description' => 'AV 9 DE OCTUBRE N° 364 (N° 374) LIMA HUAURA - HUACHO',
                'location' => 'HUAURA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 212,
                'client_id' => 127,
                'name' => 'Huancayo - PVH',
                'description' => 'AV. FERROCARRIL NRO 1021 (TAMBIEN 1035,1057) JUNIN - HUANCAYO',
                'location' => 'HUANCAYO, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 213,
                'client_id' => 127,
                'name' => 'Huaral - PVH',
                'description' => 'MZA. F LOTE 2 URB. EL ROSARIO (ZONA A) LIMA - HUARAL',
                'location' => 'HUARAL, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 214,
                'client_id' => 127,
                'name' => 'Los Olivos - PVH',
                'description' => 'AV. ANTUNES DE MAYOLO N° 961 URB MERCURIO I ETAPA',
                'location' => 'LOS OLIVOS, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 215,
                'client_id' => 127,
                'name' => 'Nvo Chimbote - PVH',
                'description' => '',
                'location' => 'KM. 424 PAMPAS DE CHIMBOTE (COLINDANTE CON EL AEROPUERTO) ANCAS SANTA - NUEVO CHIMBOTE - CHIMBOTE, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 216,
                'client_id' => 127,
                'name' => 'Supermercados SKA - PVE',
                'description' => '',
                'location' => 'JR MANUEL VILLAVICENCIO 476 ANCASH SANTA - CHIMBOTE - CHIMBOTE, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 217,
                'client_id' => 127,
                'name' => 'Alameda Sur - PVS',
                'description' => '',
                'location' => 'AV ALAMEDA SUR CRUCE AV SAN MARCOS  (FRENTE AL GRIFO REPSOL) - CHORRILLOS, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 218,
                'client_id' => 127,
                'name' => 'Bolichera - PVH',
                'description' => '',
                'location' => 'AV. TOMÁS MARSANO 5000 - SANTIAGO DE SURCO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 219,
                'client_id' => 127,
                'name' => 'Bolognesi - PVE',
                'description' => '',
                'location' => 'CALLE BOLOGNESI 447 - MAGDALENA DEL MAR, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 220,
                'client_id' => 127,
                'name' => 'Brasil - PVH',
                'description' => '',
                'location' => 'AV. BRASIL 1599 - JESUS MARÍA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 221,
                'client_id' => 127,
                'name' => 'Brena - PVH',
                'description' => '',
                'location' => 'CALLE JUAN PABLO FERNANDINI 754.  REFE.  JR. CENTENARIO  230-264. BREÑA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 222,
                'client_id' => 127,
                'name' => 'Cortijo - PVH',
                'description' => '',
                'location' => 'AV. REPÚBLICA DE PANAMÁ 515 - BARRANCO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 223,
                'client_id' => 127,
                'name' => 'Higuereta - PVH',
                'description' => '',
                'location' => 'AV. AVIACIÓN 5150 TIENDA  B URB. RESIDENCIAL HIGUERETA - SANTIAGO DE SURCO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 224,
                'client_id' => 127,
                'name' => 'Jockey Plaza - PVH',
                'description' => '',
                'location' => 'AV. JAVIER PRADO ESTE 4200 - SANTIAGO DE SURCO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 225,
                'client_id' => 127,
                'name' => 'La Molina - PVH',
                'description' => '',
                'location' => 'AV. RAÚL FERRERO 1205 URB. REMANSO II ETAPA - LA MOLINA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 226,
                'client_id' => 127,
                'name' => 'Magdalena - PVS',
                'description' => '',
                'location' => 'URB. ORBEA , JR. JOSE GALVEZ NO 780. MAGDALENA DEL MAR - MAGDALENA DEL MAR, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 227,
                'client_id' => 127,
                'name' => 'Mercaderes - PVS',
                'description' => '',
                'location' => 'AV. BENAVIDES CDRA 51 S/N - SANTIAGO DE SURCO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 228,
                'client_id' => 127,
                'name' => 'Monterrico - VIV',
                'description' => '',
                'location' => 'AV. ENCALADA CDRA.5 CON AV. ANGAMOS CDRA.5 - SANTIAGO DE SURCO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 229,
                'client_id' => 127,
                'name' => 'Multiplaza - PVS',
                'description' => '',
                'location' => 'AV. GRAU 555 (OVALO GRAU) PIURA - PIURA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 230,
                'client_id' => 127,
                'name' => 'Paita - PVH',
                'description' => '',
                'location' => 'AV. ALMIRANTE MIGUEL GRAU 514 (SUB LOTE B,C,D,E,F,G) PIURA - PAITA - PIURA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 231,
                'client_id' => 127,
                'name' => 'Puruchuco - PVH',
                'description' => '',
                'location' => 'AV. NICOLAS AYLLON 4770 - ATE VITARTE, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 232,
                'client_id' => 127,
                'name' => 'Rimac Alcazar - PVH',
                'description' => '',
                'location' => 'AV. ALCÁZAR N° 620-630 CRUCE CON CALLE CALESAS N°180 RIMAC (EX METRO) - RIMAC, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 233,
                'client_id' => 127,
                'name' => 'Risso - PVH',
                'description' => '',
                'location' => 'AV. AREQUIPA NO 2250 - LINCE, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 234,
                'client_id' => 127,
                'name' => 'Salaverry - PVH',
                'description' => '',
                'location' => 'AV. FELIPE SANTIAGO SALAVERRY S/N - INTERSECCION CON AV. PUNTA DEL ESTE - JESUS MARÍA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 235,
                'client_id' => 127,
                'name' => 'San Borja - PVH',
                'description' => '',
                'location' => 'CALLE MORELLI CDRA. 1 SAN BORJA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 236,
                'client_id' => 127,
                'name' => 'Talara - PVH',
                'description' => '',
                'location' => 'CALLE MARISCAL CASTILLA Nº220 - TERRENO URBANO TALARA (PARQ. N° 78 C.CIVICO TALARA) PIURA TALARA PARIÑAS PIURA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 237,
                'client_id' => 127,
                'name' => 'Talara Municipalidad - PVH',
                'description' => '',
                'location' => 'PARCELA A LOTE 2. PIURA-TALARA-PARIÑAS PIURA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 238,
                'client_id' => 127,
                'name' => 'Tumbes - PVH',
                'description' => '',
                'location' => 'AV. TUMBES S/N INTERS. CALLE LA MARINA TUMBES, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 239,
                'client_id' => 127,
                'name' => 'Valle Hermoso - PVH',
                'description' => '',
                'location' => 'AV. JACARANDÁ 890 URB. VALLE HERMOSO SANTIAGO DE SURCO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 240,
                'client_id' => 127,
                'name' => 'Dasso - PVS',
                'description' => 'AV. CAMINO REAL 1335',
                'location' => 'SAN ISIDRO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 241,
                'client_id' => 127,
                'name' => 'La Paz - PVS',
                'description' => '',
                'location' => 'AV. LA PAZ CUADRA 25. SAN MIGUEL, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 242,
                'client_id' => 127,
                'name' => 'La Perla - PVS',
                'description' => '',
                'location' => 'AV. SANTA ROSA N° 347 MZ 94 LOTE 2 DISTRITO DE LA PERLA CALLAO CALLAO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 243,
                'client_id' => 127,
                'name' => 'Primavera - PVH',
                'description' => '',
                'location' => 'AV. ANGAMOS ESTE 2337, SAN BORJA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 244,
                'client_id' => 127,
                'name' => 'San Isidro - PVH',
                'description' => '',
                'location' => 'PASEO DE LA REPUBLICA 3440, SAN ISIDRO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 245,
                'client_id' => 127,
                'name' => 'Chincha - PVH',
                'description' => 'CAL. ÓSCAR R. BENAVIDES S/N (SECTOR PIEDRA LA ESTRELLA) ICA - CHINCHA CHINCHA ALTA',
                'location' => 'ICA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 246,
                'client_id' => 127,
                'name' => 'Chorrillos Iglesias - PVS',
                'description' => 'AV. ALFONSO UGARTE/N,051 CHORRILLOS',
                'location' => 'CHORRILLOS, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 247,
                'client_id' => 127,
                'name' => 'Colonial - PVH',
                'description' => 'AV OSCAR R. BENAVIDES 4929 (EX AV. COLONIAL) - BELLAVISTA, CALLAO/ A 5 CUADRAS DEL CRUCE DE AV. FAUCETT Y AV. COLONIAL',
                'location' => 'CALLAO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 248,
                'client_id' => 127,
                'name' => 'Grifo Kio - PVS',
                'description' => 'PANAMERICANA SUR KM25 LURIN REFERENCIA AL COSTADO GRIFO KIO',
                'location' => 'LURIN, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 249,
                'client_id' => 127,
                'name' => 'Ica - PVH',
                'description' => 'AV. AYABACA N° 1180 FND. SAN JOSE (AV. LOS MAESTROS 231-235) ICA',
                'location' => 'ICA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 250,
                'client_id' => 127,
                'name' => 'Ilo - PVH',
                'description' => 'MZ. C LT. 1, SECTOR AV. MARIANO LINO URQUIETA, U.O. 5401, EX MEYLAN',
                'location' => 'ILO / MOQUEGUA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 251,
                'client_id' => 127,
                'name' => 'Moquegua - PVH',
                'description' => 'FUNDO EL GRAMADAL. AV. CIRCUNVALACION LOTE 1B . SUB LOTE 1',
                'location' => 'MOQUEGUA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 252,
                'client_id' => 127,
                'name' => 'San Jorge - PVS',
                'description' => 'AV. LA MOLINA 1080',
                'location' => 'LA MOLINA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 253,
                'client_id' => 127,
                'name' => 'Sucre - PVH',
                'description' => 'AV. SUCRE NRO. 550-552 PUEBLO LIBRE',
                'location' => 'PUEBLO LIBRE, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 254,
                'client_id' => 127,
                'name' => 'Tacna - PVH',
                'description' => 'S/N PARCELA 9 (SECTOR PAGO SILPAY PARCELA 3658005) TACNA',
                'location' => 'TACNA, PROVINCIA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 255,
                'client_id' => 127,
                'name' => 'Ventanilla - PVH',
                'description' => 'Z.I. CIUDAD SAT. DE VENTANILLA S/N - REF. NESTOR GAMBETA / CALLE TROMPETEROS / VENTANILLA',
                'location' => 'VENTANILLA, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 256,
                'client_id' => 127,
                'name' => 'Villa el Salvador - PVS',
                'description' => 'SUB LOTE A1 CON FRENTE A LA AV. LIMA / AV. PACHACUTEC CRUZE CON LA AV. LIMA S/ N AL COSTADO DE ELECTRA  REFERENCIA PARADERO LOS CHINOS',
                'location' => 'VILLA EL SALVADOR, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 257,
                'client_id' => 127,
                'name' => 'Villa Marina - PVS',
                'description' => 'AV. VILLA MARINA 176',
                'location' => 'CHORRILLOS, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 258,
                'client_id' => 127,
                'name' => 'Guardia Civil - PVH',
                'description' => 'LOS FAISANES ADYACENTE A LA MZ. “Z”, SUB LOTE “B”, PARCELACIÓN SEMIRÚSTICA LA CAMPIÑA',
                'location' => 'CHORRILLOS, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 259,
                'client_id' => 127,
                'name' => 'La Curva - PVH',
                'description' => '',
                'location' => 'LOTE DEP CESAR VALLEJO VMT LIMA, VILLA MARIA DEL TRIUNFO, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 260,
                'client_id' => 127,
                'name' => 'LurIn - PVH',
                'description' => '',
                'location' => 'URB. SAN VICENTE S/N. CALLE ANTIGUA PANAMERICANA SUR. PARCELA B-43, LURIN, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 261,
                'client_id' => 127,
                'name' => 'Ves Placita - PVH',
                'description' => '',
                'location' => 'MZ. K-3 LT 01 URB. PARQUE INDUSTRIAL DEL CONO SUR, V.E.S., VILLA EL SALVADOR, LIMA',
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        foreach ($data as $item) {
            SubClient::create($item);
        }
    }
}
